### ISSUE TITLE
Додайте інструкцію для користувачів GoldenDict

### ISSUE THREAD

**Issue by Symbian9** [brown-uk/dict_uk#105]
Додайте в основний файл "README.md" вказівки по встановленню данного словника у програму GoldenDict.
- http://github.com/goldendict/goldendict

**Comment by arysin** [comment]
Це цікава ідея, спробую створити на виході формат для GoldenDict.

**Comment by arysin** [comment]
Тут є таких пару моментів:
1) словник постійно розвивається, тож якщо робити знімок для GoldenDict він може відносно швидко застаріти
2) словник не є академічним довідником, він радше несе практичну цінність для застосувань в NLP тощо, тож переглядати його в GoldenDict не є надто корисним

Але на початку року ми плануємо створити веб-сторінку де можна буде переглядати слова в цьому словнику.

**Comment by arysin** [comment]
Все ж таки є більший сенс зробити веб-інтерфейс поверх наявного REST API (див. #114)
