### ISSUE TITLE
Помилка у readme файлі?

### ISSUE THREAD

**Issue by vicner** [brown-uk/dict_uk#106]
'Словник містить слова та їх парадигми'
Неправильна форма 'їх', тут треба 'їхні'. 
Чи можна на 100% довіритись такому словнику? Питання відкрите...

**Comment by vicner** [comment]
Не академічний приклад, проте, думаю, згодиться:
https://ukr-mova.in.ua/library/antusurzhuk/yix-i-yixnij

**Comment by arysin** [comment]
Дякую, виправив. На 100% жодному словнику довірятися не можна, зрештою і не тільки словнику :)
Але словник відкритий, дещо протестований на реальних завданнях, і приймає запити на виправлення. :)
