### ISSUE TITLE
Додати можливість генерувати розмовні вкорочені форми дієслів

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#111]
пита, любе, ходе...

**Comment by vstarko** [comment]
пита, зна, віда - справді розмовна вкорочена форма, а от любе й ходе - це вже просторіччя (неправильно утворені форми). Перші варто буде генерувати, а другі - ні. Їх можна хіба що в покручі записати - та й то лише ті, що справді часто вживаються.

**Comment by arysin** [comment]
Зроблено
