### ISSUE TITLE
How can I generate Ispell files?

### ISSUE THREAD

**Issue by ktaras** [brown-uk/dict_uk#119]
Hey!
I'd like to use this dictionary for PostgreSQL full text search, so I need to generate one single .aff file and one single .dic file to add them to Postgres as described here: https://www.postgresql.org/docs/current/static/textsearch-dictionaries.html#TEXTSEARCH-ISPELL-DICTIONARY

I didn't find any tips in Readme. Is it possible? Could you please help me with it and write some manual?

**Comment by arysin** [comment]
We can generate hunspell files. They are slightly different than ispell but it seems that PostgreSQL should support those:
gradle -p distr/hunspell hunspell
the *.dic and *.aff files will be in distr/hunspell/build/hunspell

It should work as is now but I am in the process of cleaning some things up so you may want to update the files in a day or two.

**Comment by arysin** [comment]
It should all good now:
https://github.com/brown-uk/dict_uk/tree/master/distr/hunspell

**Comment by ktaras** [comment]
Thanks!
I've tried to run that command but I got error:
```
Exception in thread "main" java.io.FileNotFoundException: build/hunspell/uk_UA.aff (No such file or directory)
```
I've manually created the folder `hunspell` and it worked! Perhaps it should be added to git repo?

But anyway thank you! You've been doing a great job!

**Comment by arysin** [comment]
Thanks, I've fixed build script to create that directory.

**Comment by ktaras** [comment]
@arysin sorry, but it seems broken again.
```
Exception in thread "main" java.io.FileNotFoundException: ../../data/dict/composite.lst (No such file or directory)
```

**Comment by arysin** [comment]
My bad, pushed another fix.
BTW I also added hunspellForSearch task that also includes some barbarisms, if you're doing search rather than spelling you may want to use that.
