### ISSUE TITLE
Проставити власну назву в абревіатурах

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#12]

**Comment by msklvsk** [comment]
`pcregrep "^\S.*abbr" out/dict_corp_vis.txt | pcregrep "prop"`
<pre>
СНД noun:inanim:m:v_naz:nv:np:prop:abbr
СРСР noun:inanim:m:v_naz:nv:np:prop:abbr
</pre>

Лише вони? а як же НАТО?

**Comment by arysin** [comment]
Є таке, тре переглянути.

**Comment by msklvsk** [comment]
Якщо в абревіатурі немає вкінці “У” (України) то це не дуже вже й `:prop`? якщо може бути не тільки в Україні. Типу МВС може бути і Молдовське.
Як тоді бути з 
<pre>ДДСО noun:f:nv    # Державна служба охорони
ДІНЗ noun:f:nv    # Державна інспекція навчальних закладів
ДКЦПФР noun:f:nv    # Національна комісія з цінних паперів та фондового ринку</pre>

І ДСТУ — це `:prop`?
