### ISSUE TITLE
Spelling correction

### ISSUE THREAD

**Issue by aotenko** [brown-uk/dict_uk#123]
Слово "суперїжа", здається, суперечить чинному правопису. Між приголосним та ї ставиться апостроф, зокрема між основами в складних словах, та після префіксів. Якщо немає авторитетного джерела, яке зазначає інше, треба виправити, і вставити апостроф між супер та їжа.

**Comment by arysin** [comment]
Дякую, виправив, разом з декількома іншими випадками.
