### ISSUE TITLE
Можлива помилка

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#124]
Можливо, додати як небажане "З тих пір" і натомість "Відтоді", чи це більше пуризм, ніж помилка?

**Comment by arysin** [comment]
Дякую, додано. Хоча у цьому словнику обробляються лише окремі слова, тож якщо є покруч, або його заміна можна писати тут. Якщо є пропозиція для сполук, то це краще звітувати тут https://github.com/languagetool-org/languagetool/issues з позначкою `[uk]` в темі

**Comment by OnaHe** [comment]
Я додав на те посилання, що ви дали, пропозицію​. Це туди треба було таки
писати, чи тут?

**Comment by arysin** [comment]
Нові слова або помилки в словах треба звітувати тут, бо слова та їх відмінювання реєструються в цьому словнику. Фрази, сполуки тощо — в languagetool, бо LT опікується правилами сполучення слів тощо.

**Comment by OnaHe** [comment]
Зрозуміло, дякую.
