### ISSUE TITLE
[uk] Додати слово

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#126]
Писав там, де ви вказали, але не зреагували, тож напишу тут:
співдиректором, співдиректор, Фенноскандія, оберненояйцевидий, декомунізація, декомунізували, декомунізований, збанкрутів, природній наразі показує як неправильне, хоча це помилка, Йоана додати

**Comment by arysin** [comment]
оберненояйцевидий — не знайшов у жодному словнику, що це таке?
збанкрутів — правильно збанкрутував
природній — помилка, правильно природний
решту — додамо

**Comment by vstarko** [comment]
банкрутіти, збанкрутіти, збанкрутілий - нормально утворені слова. Караванський подає такі, на чтиво трапляється. Можна подати.
природній - внести як :bad - типова помилка

**Comment by OnaHe** [comment]
http://onlinecorrector.com.ua/%D0%BF%D1%80%D0%B8%D1%80%D0%BE%D0%B4%D0%BD%D0%B8%D0%B9/
а це щодо природній/природний? До того ж, слово наявне в словниках
українізації, звідси "написане не за чинним правописом", а не "помилка".
подайте тоді збанкрутів як неправильне
оберненояйцевидий - це з біології. помилково багато хто говорить
оберненояйцеподібний

10 квітня 2017 р. о 18:40 vstarko <notifications@github.com> написав:

**Comment by arysin** [comment]
"природній" у нас вже є, як bad, з заміною на "природний", але також пам'ятайте, що "природній" є правильною формою д.в. та м.в. ж. р. від "природний"
банкрутіти та збанкрутіти — додамо
щодо «оберненояйевидий» то «яйцеподібний» (та «яйцюватий», «яйцевий») є правильними формами, див. Науковий англо-український словник http://e2u.org.ua/s?w=%D1%8F%D0%B9%D1%86%D0%B5%D0%BF%D0%BE%D0%B4%D1%96%CC%81%D0%B1%D0%BD%D0%B8%D0%B9&dicts=all&highlight=on
Зокрема цей словник подає 
**obovate** обе́рнено яйцеподі́бний
**obovoid** обе́рнено яйцеподі́бний

**Comment by OnaHe** [comment]
Також, додати до словника: "налаштунок", "налаштунки", "ваблень" (ваблення),

**Comment by arysin** [comment]
І СУМ (http://sum.in.ua/s/plodolystyk), і УЛІФ (http://lcorp.ulif.org.ua/dictua/), і Граматичний словник (http://www.mova.info/grmasl.aspx) подають саме "плодолистика" (і "плодолистики").

**Comment by vstarko** [comment]
Словник біологічної термінології (Паночіні С. Харків, 1931), УРЕ (Т. 8, 1982) і wikipedia (яка згода крізь епохи!) подають "плодолисток". Цей термін має таке саме (якщо не більше) право на існування, як "плодолистик". Шкода, що СУМ, УЛІФ і Граматичний словник не знають цього слова.

**Comment by OnaHe** [comment]
Ті словники застаріли ше з часу падіння комунізму. Гадаю, оте слово може
подати як можливе, або як таке, що не за чинним правописом. У будь-якому
випадку, воно має право на існування.

11 квіт. 2017 р. 12:34 "vstarko" <notifications@github.com> пише:

**Comment by arysin** [comment]
Я додав майже всі запропоновані слова (разом з декількома сотнями інших). Щоправда в LanguageTool вони потраплять трішки згодом.
Щодо «природній» я подивлюся на правила, щоб його краще виловлювати.

**Comment by OnaHe** [comment]
Дякую.

14 квітня 2017 р. о 03:55 arysin <notifications@github.com> написав:
