### ISSUE TITLE
Неясність

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#127]
Скажіть, чи правильно, що виправляє первіснообщинний - на первісногромадський? Це ж різні значення наче, ні?

Також, додайте: Гесіода, Геосід, Гесіодом, Кронос, найзіпсутіші, общинників, общинники, Мікен, доземлеробські, массініків (массиніків?).

П.С. Що це за слово "оплот"? може замінити на "твердиню/передму́р’я", залежно від контексту?

**Comment by arysin** [comment]
Коментар від мовознавця:
"Община" може бути прийнятним  хіба що як варваризм на позначення сільської громади в Росії. В інших (загальних) значеннях  правильно "громада" й похідні від неї. Тому первісногромадський - те, що треба. Значення відповідне. Цього відповідника подає (щоправда на другому місці) навіть академічний РУС у 4-х тт. (2011-2014).

**Comment by arysin** [comment]
А що таке массиніки?

**Comment by OnaHe** [comment]
Щось пов'язане з церквою. Вчора на Вікіпедії надибав.

14 квіт. 2017 р. 23:19 "arysin" <notifications@github.com> пише:

**Comment by OnaHe** [comment]
Додайте ще "стрит", а "стріт" вкажіть як неправильне, відповідно до §
114.3.г

15 квітня 2017 р. о 07:35 OnaHe <oglaignaheireann@gmail.com> написав:

**Comment by OnaHe** [comment]
І ще: Оріховський, Оріховського, дослуховувався, нашіптувачів, Аристофана, Цицерон (подайте Ціцерон як небажане), дослуховуються, томізму, Гієронімом,  слово _обгрунтування_ позначте як неправильне і подайте як правильне - обґрунтування.

**Comment by OnaHe** [comment]
Взагалі, може зробити постійну тему, де люди вказуватимуть нові слова?

**Comment by arysin** [comment]
Щодо Прусія то тут не все однозначно, ß передає один звук [s], але відповідає подвоєній літері s на письмі, зокрема див. обговорення тут https://www.facebook.com/groups/ukrpereklad/permalink/1305448139490951/?match=0LPQtdGA0YbQvtCz0YHRgtCy0L5f0L%2FRgNGD0YHRltGPXyzQv9GA0YPRgdGW0Y8%3D

**Comment by OnaHe** [comment]
А як же словники?

20 квіт. 2017 р. 23:36 "arysin" <notifications@github.com> пише:

**Comment by arysin** [comment]
На жаль словники не завжди дають однозначну відповідь:
1) словники можуть суперечити один одному
2) словники можуть суперечити правопису
3) можуть просто мати помилки
Тож зі словниками ми обов'язково звіряємося, але повністю не довіряємо жодному :)

**Comment by arysin** [comment]
Одна тема для всіх слів дуже швидко розбухне, бо слів тисячі. Краще створювати тему на групу слів, коли слова додані в словник, тему закриваємо.

**Comment by arysin** [comment]
доєднаний — на знайшов такого в словниках
обґрунтування/обгрунтування — ці пари вже є

**Comment by OnaHe** [comment]
Файно.

21 квіт. 2017 р. 19:49 "arysin" <notifications@github.com> пише:

**Comment by OnaHe** [comment]
Ще таке: слово "марширувати" - калька з російської. Чи можливо замінити на "маршувати"/"машерувати"?

**Comment by OnaHe** [comment]
ще додайте: гусами, яйцевиді, самозапилюються, опушенням, каудексом, каудексових,

**Comment by OnaHe** [comment]
так само: додайте Магатмою, Магатма, Ганді позначте як небажане, а натомість додайте Ґанді.

**Comment by arysin** [comment]
гусами — не знайшов такого в словниках, це що таке?
яйцевидий — яйцюва́тий, яйцеподібний
самозапилюються  — ок
опушувати — [росіянізм](http://r2u.org.ua/s?w=%D0%BE%D0%BF%D1%83%D1%88*&scope=all&dicts=all&highlight=on)
каудекс,  каудексовий — ок
Магатма, Ґанді — ок

P.S. до речі, краще пропонувати початкові форми слів (леми), а не похідні

**Comment by OnaHe** [comment]
гусами - це похідне від гуси

26 квіт. 2017 р. 05:44 "arysin" <notifications@github.com> пише:

**Comment by arysin** [comment]
орудний від гуси буде — гусьми, див.
http://lcorp.ulif.org.ua/dictua/
http://www.mova.info/grmasl.aspx
http://r2u.org.ua/s?w=%D0%B3%D1%83%D1%81%D0%B8&scope=all&dicts=11&highlight=on

**Comment by arysin** [comment]
маршир* будемо пропонувати міняти на марш*, дякую

**Comment by OnaHe** [comment]
скажіть, а коли з’являться ті оновлення?

2017-04-26 20:54 GMT+03:00 arysin <notifications@github.com>:

**Comment by arysin** [comment]
Як правило зміни у словник ми групуємо, коли назбирується значна кількість, ми проганяємо зміни на регресійних тестах на великих архівах, якщо все гаразд, тоді закидуємо в перевірку.
На http://r2u.org.ua/check такі зміни потрапляють переважно за тиждень-два (інколи частіше), в офіційний репозитарій LanguageTool десь перед випуском нової версії (раз на три місяці).

**Comment by OnaHe** [comment]
Ви постійно додаєте нові слова, чи лише коли є пропозиції?

27 квіт. 2017 р. 00:07 "arysin" <notifications@github.com> пише:

Як правило зміни у словник ми групуємо, коли назбирується значна кількість,
ми проганяємо зміни на регресійних тестах на великих архівах, якщо все
гаразд, тоді закидуємо в перевірку.
На http://r2u.org.ua/check такі зміни потрапляють переважно за тиждень-два
(інколи частіше), в офіційний репозитарій LanguageTool десь перед випуском
нової версії (раз на три місяці).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/brown-uk/dict_uk/issues/127#issuecomment-297541483>,
or mute
the thread

**Comment by arysin** [comment]
Додаєм постійно, десь по декілька тисяч слів на кожний випуск LT (раз на три місяці). Зараз маємо список з декількох десятків тисяч нових слів, що є в інших добрих джерелах, але навіть ті треба переглядати і перевіряти, що вимагає багато часу.
Насправді, ефективніше додавати нові слова великими групами, але часто, додаємо і окремими групками, особливо ті, що не просто в словниках, а дійсно зустрічаються в текстах.

**Comment by arysin** [comment]
Слова з цієї гілки завантажено на http://r2u.org.ua/check

**Comment by OnaHe** [comment]
Дякую.

10 трав. 2017 р. 15:39 "arysin" <notifications@github.com> пише:
