### ISSUE TITLE
Моя подяка за допомогу у створенні бази рим

### ISSUE THREAD

**Issue by fox-dgv** [brown-uk/dict_uk#128]
Вельми вдячний за цю базу. Я створюю аналогічний проект - базу рим української та російської мов.  Хоча мені не потрібні зарозумні терміни, хімія, медицина та подібне (база для поетів, потрібні більше широковживані слова), все ж багато відсутніх словоформ мою базу доповнять. Десь мільйон слів ще треба обробити вручну (проставити наголоси), але я впораюсь. В мене вже була сформована велика база, але словоформи в багатьох випадках були відсутні.
В цій базі багато помилок, русизмів, але мені не звикати. З моїм проектом можна докладно ознайомитись тут:
http://www.stihi.in.ua/avtor.php?author=46487&poem=126810
База рим роздається всім бажаючим, безкоштовно. Аби була корисна людям, які хочуть виявити себе в поезії.

**Comment by arysin** [comment]
Дякуємо за теплі слова, наснаги вам до вашого проекту!

**Comment by fox-dgv** [comment]
Moжу поділитись даними. Вони в простенькому DBF, але там є легка можливість побудувати наголоси для слів, бо база рим як раз і базується на групуваннях за допомогою наголосів. В посиланні на проект є поштова адреса. Я планую і далі використовувати Ваші дані, то ж пропоную і свої послуги. У мене в базу втягнуто багато слів (більше 1,6 млн.) з різних джерел, в тому числі і багато з літературних творів, наукових, філософських тощо.

**Comment by arysin** [comment]
Дякую, тоді маю декілька питань. Чи є ця база десь у відкритому доступі (на гітхабі чи іншій відкритій платформі)? І на які словники ви взорувалися, коли додавали наголоси, бо в інколи це досить «сіра» територія.
Теоретично я інколи розмірковую чи не варто додати інформацію про наголоси в наш проект, але наші сирці оперують нормалізованими записами (лема + прапорці відмінювання), тож не впевнений, що можна буде легко наголоси там інтегрувати.

**Comment by fox-dgv** [comment]
Пояснюю. Я базу просто роздаю бажаючим, коли вони пишуть мені на пошту запит. Оновлені копії викладаю на Google Drive, підписники завантажують собі копію і все. База працює локально, програма написана на Visual FoxPro, формат даних - DBF. Структура дуже проста:
В таблиці два поля, приклад рядка:
Word, Rhyme
грати, -ати
Зрозуміло з погляду на запис, що наголос в слові "грати" на третій літері справа. Так можна сформувати інші бази на основі цієї, де є наголоси. Групування слів базується на однаковому значенні в записах поля Rhyme. Тобто слова "грати, взяти, мати, вати, продукувати..." мають в полі Rhyme значення "-ати". Все дуже просто.
На сторінці з описом проекту http://www.stihi.in.ua/avtor.php?author=46487&poem=126810 все більш детально.
Ось остання копія, яку я вчора виклав для нового користувача, який звернувся до мене, прочитавши тут моє повідомлення: https://drive.google.com/file/d/0By33J2MaFJjmU1VkRXpMRkJvWlU/view?usp=sharing
Як я її створював? Почав з російської. В основу заклав словник Залізняка з наголосами та словник Хагена. Там, де не було наголосів, проставляв вручну. Коли було потрібно, дивився наголоси на http://udarenieru.ru.
Потім, через три роки, заклав основи української бази. В основу лягли дані одного знайомого хлопця, який в свою чергу десь зумів витягти щось подібне до Ваших даних. Консультуюсь я відносно наголосів, коли мені потрібно, на http://lcorp.ulif.org.ua/dictua.
Далі процес пішов таким чином. Для обох баз я шукав різноманітні словники, розбирав їх на слова, втягував, а потім вручну ставив наголоси. Потім дійшла черга до електронних бібліотек. Були втягнуті великі обсяги самої різної літератури, потім оброблені. Навіть Велику Радянську Енциклопедію розібрав на слова на повністю втягнув. Зараз в чорновій базі обробляються дані Вашої бази та великий масив втягнутої української літератури з електронної бібліотеки.
Бази ще не вичитані, але працюють. Вже багато поетів користуються.
Чим може бути корисна Вам база? В першу чергу новими словами, яких в Вашій базі немає (бо я ж тягнув багато звідки). Стосовно наголосів - вони ставляться вручну, мною. Самі розумієте, це треба вичитувати. Все робиться тільки однією людиною - мною, на це теж треба зважати.
Я просто пропоную свої дані. Чи схочете брати, чи ні - то справа Ваша. Я скористаюсь Вашими, вони мені корисні, за що дякую.

**Comment by fox-dgv** [comment]
Ще трішки про себе. 51 рік, в ІТ 25 років. Майже стільки ж працюю з FoxPro. Базу роблю перш за все для себе, бо сам ще й поет. Побачити збірку можна там же, на сторінці з проектом. Окрім цього, системник.
Як я втягнув Вашу базу на обробку. Ніяких Ваших програм я не запускав. Ваші файли bz2 розпакував WinRARом. Далі отримані txt перезаписав з UTF в ANSI за допомогою Notepad. В файлах побачив три поля. Втягнув в таблицю FoxPro звичайною командую append from. В третє поле пішли Ваші технічні дані, вони мені не потрібні, а в перші два поля - слова. Далі - справа звична, експорт в чорнову базу проекту та подальша обробка слів в частині проставляння наголосів.
Як оброблю цей масив (разом з імпортом з електронної бібліотеки зараз більше 1,5 млн. слів), знов зроблю таку втяжку. Щось корисне і нове знову доповнить мою базу. Я не беру все підряд. В поезії хімія, медицина або суржик (а він є у Вас в базі) не потрібні, потрібні широковживані словоформи.

**Comment by arysin** [comment]
Дякую. я стягнув вашу базу.

**Comment by fox-dgv** [comment]
Эх, якби ж десь вдалось знайти цю базу:
 http://lcorp.ulif.org.ua/dictua
Зараз ставлю вручну наголоси в Ваших даних та своїх, дуже довго та важко. Та ніхто не дасть. А от в Рассєє можна стібрити багато чого, не жадібні і розуміють, що "продвіжєніє руського міра" - важливе завдання. А в нас або якісь дурні djvu-файли, або давай гроші.

**Comment by fox-dgv** [comment]
Може Вас таке зацікавить як джерело нових слів. Дампи української Вікіпедії. Вони великі, біля 8 Гб, тож я простими інструментами не розкурочу.
https://dumps.wikimedia.org/ukwiki/20170420/

**Comment by arysin** [comment]
Я працював трішки з базою вікіпедії пару років тому, але вона має декілька недоліків для створення словника:
1) там велика кількість власних назв, зокрема закордонних
2) там велика кількість історичної лексики
3) там страшна купа помилок; я навіть деякий час виправляв статті з найочевиднішими помилками
Можливо колись ще повернемося до вікіпедії, але як інші, ґрунтовніші, джерела буде вичерпано

**Comment by burunduk** [comment]
Я що до слів з фантазійної тематики, для них знайдеться місце в словнику? Чи там будуть проблеми із походженням?

**Comment by arysin** [comment]
Фантазійна — це досить специфічна тематика, в словник я додавав би хіба, якщо слово почало широко вживатися, за межами пари книжок.

**Comment by fox-dgv** [comment]
Я додаю всі слова, які вживаються людьми в побуті, в літературі, в мистецтві хоч якось, хоч іноді. В тому числі і сучасні, в тому числі щодо персонажів казок, фільмів тощо. В базі заважатимуть занадто специфічні терміни або назви якихось маловідомих сел тощо. Заважатимуть, бо сама база призначається для поезії, там не треба групи рим захаращувати словами, які в поезії просто аж ніяк не використовуються.
До речі в Ваших даних помилок хмара. Наприклад, "бистроумний" - подвійний суржик. Отже Вікіпедія не набагато гірша.

**Comment by arysin** [comment]
Дуже рідковживані, зокрема вигадані книжкові слова можуть створювати проблеми, як для перевірки правопису/граматики, так і для інших вживань (зокрема цей словник незабаром вживатиметься для повнотекстового пошуку у Вікіпедії), тому є деякі області звідки ми слова беремо дуже обережно.
Щодо помилок хмара — я проти такої гіперболізації :), цей словник звірявся з іншими поважними словниками і сумнівні моменти дискутувалися з лінгвістами. Тобто помилки, звичайно будуть, без них не буває, але їх дуже мало, я б навіть сказав, менше ніж в деяких інших відомих словниках. :)
Щодо бистроумний, то це слово є в [АС](http://r2u.org.ua/s?w=%D0%B1%D0%B8%D1%81%D1%82%D1%80%D0%BE%D1%83%D0%BC%D0%BD%D0%B8%D0%B9&scope=all&dicts=all&highlight=on), а також в УЛІФі. Якщо ви вважаєте, що це суржик, та ще й подвійний, то буду вдячний за обґрунтування, але вважайте, в українській мові [є купа слів, на бистр-](http://r2u.org.ua/s?w=%D0%B1%D0%B8%D1%81%D1%82%D1%80*&scope=all&dicts=all&highlight=on)

**Comment by arysin** [comment]
До речі щодо Вікіпедії, нещодавно майже випадково відкрив (добру) статтю «Українська мова» і знайшов там [майже 20(!) орфографічних помилок](https://uk.wikipedia.org/w/index.php?title=%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%BC%D0%BE%D0%B2%D0%B0&diff=prev&oldid=20188691).
Якщо це спроектувати на гігабайти цілого архіву, то виникає досить серйозна робота з відсіювання таких помилкових слів. Це плюс наявність величезної кількості (неукраїнських) власних назв робить Вікіпедію не найкращим джерелом поповнення базового словника для NLP.

**Comment by fox-dgv** [comment]
Я просто звернув увагу, що стан Ваших даних аж ніяк не кращий, ніж у Вікі. Повірте, я прямо зараз йду  по реєстру та виставляю наголоси. Іноді це просто жах, "мне па-руськи какось льогше", іноді відверті помилки. Якщо дані треба звідкілясь брати, нікуди не дінемось, маємо формувати чорновий словник, який треба читати перед втягуванням. Готових даних нема і ніхто не дасть, в кого вони є.
В мене зараз 2,5 млн. слів на обробці, разом зі словами для російського словника (теж дібрався до їх відкритого корпусу). Доведеться читати ці два чорнових реєстри і ставити наголоси, відсікати дурню тощо.

**Comment by arysin** [comment]
Десь півроку тому ми добряче почистили словника. Тож, якщо ви маєте останню
версію нашого словника і бачите помилку створюйте issue на гітхаб і якщо це
дійсно помилка ми її виправимо.

**Comment by fox-dgv** [comment]
Помилок дуже багато. Є просто помилки. Бачив, наприклад, "транспорна". Є русизми типу "гуркотливий" або "агентство". Якщо я буду все Вам дописувати, не буду часу проставляти наголоси. В мене теж база ще не вичитана, але Ваші дані вже вичитую по дорозі перед втягненням. Наприклад, "культиваторщик". "Культиваторник" має бути. Або "одержувач". Має бути "отримувач", та ще в споріднених словах - "авансоотримувач". "Необоротні кошти"? - "Необігові кошти".
Дуже відчувається, що хтось з Донецька "попрацював" над деякими групами слів. Далеко не все беру, але багато. Дуже сильно заважають назви селищ, які нікому майже не відомі, але в назвах є русизми тощо.
Я, як втягну Ваші дані, свою базу вичитаю. Всі ці "перли" будуть нещадно видалені, плювати на корпуси та словники. В тому числі і форми, які є наслідком русифікації, типу: "приймаєм", "приймаємся", "прийматимем". Це з серії так званих "в'ївшихся до невпізнаваності русизмів". В моїй базі я все це видаляю. Це не мова поета, це не мова літератора. В мові літератора це: приймаємо, приймаємось, прийматимемо.
Як перероблю, то далі вже буде легше. Як зараз з російською базою. Втягнув корпус, просто гортаю. Коли трапляється, що в мене немає словоформи, тоді ставлю наголос і втягую. Так буде і з Вашими даними. У другом колі вже буде легше, тільки передивлятись буде потрібно.

**Comment by arysin** [comment]
Дякую, "транспорна" вилучив, "культиватощик", щоправда, не знайшов.

**Comment by fox-dgv** [comment]
Зараз втягую вже частину, в якій слова починаються з "в". Проблема "у-в", як я її називаю у всій своїй красі - там, де потрібно "у", стоіть "в", потім буде навпаки, коли дійду до слів на "у". База не вичитана зовсім, стан жахливий, хоча й корисний для мене, бо є купа словоформ побутової мови, яких в мене немає. Але втягується з цього всього масиву ледве відсотків тридцять. Це не академічна українська мова. На жаль моя база лише тільки формується, вона була в ще гіршому стані, теж формувалась "програмно", але не мною, тому я ще поки не можу сказати, що в мене словник академічної гарної побутової мови. Якось вичитаю з часом.
Бачив ще помилки, десь в частинах "а" та "б", можете відловити їх за наявністю "іі" в словах (в суфіксах).
Ну а суржик... Ця боротьба зі словниками, написаними "особами духовного званія" з Москви, ще попереду. Поки що воюю з безграмотними поетами. Верещать про "шевченківську мову", тобто про суржик Шевченка, наче їх ріжуть, коли тикаю їх носом. Але дослуховуються все ж.

**Comment by fox-dgv** [comment]
Стосовно "культиваторщик". Тут я більше натякаю, що така словоформа - русизм. Не "-аторщик", а "-аторник". Ця група у Вас величенька буде, включно з "-аторщицями". І так далі.
В мене, на жаль, життя не вистачить сформувати та вичитати свої російську та українську бази, та ще й Вашу вичитати без програмної оболонки. То ж шукайте філологів, які не будуть як барани повторювати дурниці в словниках та молоти дурню про багатство мови (я це чув не раз), та, що більш важливе, не вчили українську у Львові або Донецьку. Що там, що там стан мови просто жахливий, філологи звідти академічну мову просто калічать, навіть не розуміючи цього.
Я теж не філолог, а програміст. Більше того, я російськомовний. Але навіть мені видно всю цю дурню, тобто бачу її в межах програми середньої школи, в якій я вчився 35 років назад. Ось такий насправді стан Вашої бази.

**Comment by turbo-cafe** [comment]
проект словника наголосів https://github.com/turbo-cafe/acc
