### ISSUE TITLE
Чергові слова

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#129]
Імануїл, Ґолдштайн, Чаррінґтон, Парсонс, Ааронсон, Гакслі (Хакслі треба позначити як нерекомендоване/помилкове), Амплфорт, емпатуючи, каудекс, 

Це з "1984" Орвелла, переклад 2015 року.

**Comment by OnaHe** [comment]
Також, додати до виправлених варіянтів "так як" слово "позаяк".

**Comment by arysin** [comment]
Імануїл, за чинним, має бути з двома.
Чаррінґтон не знаю чи варто додавати, дуже рідко зустрічається, як прізвище, частіше, як назва готелю, тож якщо додавати то два омоніми.
емпатуючи — не знайшов у словниках, напевне від емпатувати, але теж не бачу
каудекс — вже є
позаяк — це галицизм, в словнику у нас воно є, але чи варто подавати, як заміну не впевнений
решту додав, дякую

**Comment by OnaHe** [comment]
"позаяк" звичайне слово, тож треба додати.

1 трав. 2017 р. 16:57 "arysin" <notifications@github.com> пише:

**Comment by vstarko** [comment]
підтримую: позаяк - не галицизм, варто додати

**Comment by arysin** [comment]
гаразд, додамо
