### ISSUE TITLE
Нові слова

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#131]
іредентист, Роверето, Етторе, італізація, провість, райхсрат

**Comment by OnaHe** [comment]
Ісократ, Горгій, Лікург, Гіперід, Ефор, Феопомп

**Comment by int-ua** [comment]
внескодавець?

**Comment by OnaHe** [comment]
Нормальне слово, ніц йому не бракує.

13 трав. 2017 р. 12:25 "Serhiy Zahoriya" <notifications@github.com> пише:

**Comment by int-ua** [comment]
так, мені теж так здається, треба було таки дописати, що це я пропоную його додати :) Я ж правильно розумію, що його немає зараз якщо LanguageTool його не розпізнав?

**Comment by OnaHe** [comment]
Якщо не розпізнав, то так, нема.

13 трав. 2017 р. 14:05 "Serhiy Zahoriya" <notifications@github.com> пише:

**Comment by OnaHe** [comment]
Редактор, певне, помилково вказав, що "чтива" в цьому контексті має бути "читво": 
що відносилися до розряду «чтива»

Виправте, якщо це помилка.

**Comment by OnaHe** [comment]
Також, правильне "Гічкока" виправляє на "Хічкока".

**Comment by burunduk** [comment]
Гальванік - професія людини, що займається гальванічними процесами.
Гатлінг - прізвище винахідника
Кордит - тип бездимного пороху
Інвар - сплав заліза з нікелем
Нітинол - сплав титану і нікелю
Бронярство - от тут просив би, за можливістю порадити, чи є таке слово, чи це те саме що і зброярство? До речі самого зброярства теж немає в словнику.
Скрайбування - на кшталт фрезерування, але «продряпування» деталі, і саме обладнання - Скрайб
Екзоскелет.

**Comment by OnaHe** [comment]
Є "зброяр", отже й похідне - "зброярство" теж мало би бути.

14 травня 2017 р. о 09:22 Olexandr Nesterenko <notifications@github.com>
написав:

**Comment by arysin** [comment]
прийом — покруч, див. http://r2u.org.ua/s?w=прием
моральнісний — знайшов в УЛІФі, схоже термін новий (http://ua-etymology.livejournal.com/15573.html), але можна додати
чтиво — http://r2u.org.ua/s?w=чтиво
у Вікіпедії «Гичкок», це, схоже, ближче до оригіналу
бронярство — ніде не знайшов, навіть в гуглі

решту загальних додав, дякую, власні перегляну трішки пізніше

**Comment by OnaHe** [comment]
Так а що на заміну дати в "етичні прийоми Ісократа"?

16 трав. 2017 р. 15:29 "arysin" <notifications@github.com> пише:

**Comment by arysin** [comment]
для "етичні прийоми Ісократа" я б вжив або «способи» (так подають всі допогромні словники), або Караванський ще пропонує «засоби»: 

> ПРИЁМ (художній) за́сіб

**Comment by OnaHe** [comment]
пане @arysin, а можливо дати на церковні слова (архистратиг, архимандрит, архиєрей тощо) позначку "не за чинним правописом", а не неправильно?

**Comment by OnaHe** [comment]
економлячи час, ви могли б додати імена філософів, якби я надав вам знимки змісту книги, де вони є? я часто з ними маю справу, а вони вічно позначаються червоним і незручно при перевірці щораз нові вписувати.
п.с. якшо таке можливо, світлини скину дещо пізніше.
додайте поки "Плотін"

**Comment by OnaHe** [comment]
І також, можливо неправильну конструкцію, яку часто зустрічаю "Знаходиться у" виправляти на "Розташований у, Розміщений у, Є в" тощо?

**Comment by OnaHe** [comment]
Також, звертаю вашу увагу на слово "гуральня", яке не виділяється як неправильно. Воно має виділятись як неправильне і натомість писатись "ґуральня" (про це навіть СУМ каже), тож прошу виправити.

**Comment by arysin** [comment]
Щодо гуральня то допогромні словники, як і УЛІФ подають обидві форми тож я б сказав це паралельні форми:
http://r2u.org.ua/s?w=%D0%B3%D1%83%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8F&scopeall&dicts=all&highlight=on

**Comment by OnaHe** [comment]
Посилання на світлини, де є назви філософів, які треба додати (поки що антична філософія).

![01](https://cloud.githubusercontent.com/assets/26929324/26286759/7f3aa054-3e75-11e7-8d68-eabc04791704.jpg)
![02](https://cloud.githubusercontent.com/assets/26929324/26286760/7f3b9ff4-3e75-11e7-99a8-cacd07a4fa95.jpg)

**Comment by OnaHe** [comment]
додати слово "завше", "одміна" (відміна), згідливіший, красоти.

**Comment by arysin** [comment]
> пане @arysin, а можливо дати на церковні слова (архистратиг, архимандрит, архиєрей тощо) позначку "не за чинним правописом", а не неправильно?
гаразд, додамо

**Comment by arysin** [comment]
Можна, але це все ж таки до LanguageTool, треба писати правило, бо скажімо
«знайшовся» часто буде правильним ужитком, а «знаходитиметься» — ні, тож
треба реагувати на контекст.

20 травня 2017 р. о 03:56 OnaHe <notifications@github.com> написав:

**Comment by OnaHe** [comment]
додайте, коли ласка, "Ґреммі".

**Comment by arysin** [comment]
дякую, додав Ґреммі, стикер, стікер — незабаром буде на сторінці

**Comment by arysin** [comment]
дякую, додав: "завше", "одміна" (відміна), згідливіший, красоти

**Comment by OnaHe** [comment]
філософів зі світлин додали?

2017-05-29 16:29 GMT+03:00 arysin <notifications@github.com>:

**Comment by OnaHe** [comment]
також, як щодо слова "пропонова", варте, аби його додати до словника?

**Comment by arysin** [comment]
Власні назви поки не додавав, особливо неукраїнські треба добре переглядати.
Щодо «пропонова» то я не знайшов його в жодному словнику і в архіві друкованих медій, не впевнений, чи варто

**Comment by OnaHe** [comment]
це новотвір, тому й не знайдете.

31 травня 2017 р. о 16:47 arysin <notifications@github.com> написав:

**Comment by OnaHe** [comment]
а можна ще "в якості" позначити як неправильне і дати "як"?

**Comment by arysin** [comment]
У нас вже є правило для «в якості», якщо не працює, давайте знати

**Comment by OnaHe** [comment]
сьогодні саме не знайшов, але що тоді було, який текст - не згадаю


2017-06-01 20:04 GMT+03:00 arysin <notifications@github.com>:

**Comment by arysin** [comment]
додав майже всіх філософів, днями оновлений словник буде на сторінці

**Comment by OnaHe** [comment]
вдячний

2 черв. 2017 р. 22:21 "arysin" <notifications@github.com> пише:
