### ISSUE TITLE
Слова

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#134]
додайте, будь ласка: силовики, силовиків, просп., БТРи, БТРів.
спецназ точно неправильне слово?

Так само, хотів дешо писати стосовно назв російських міст, де колись і тепер проживають українці, але їхні назви зрусифіковано.
Белгород (укр. Білгород), Таганрог (укр. Таганріг), Брест (укр. Берестя). Можливо, варто дати в дужках як небажане вживання Бєлгород, Таганрог і Брест і дати правильне, ті що я надав вище? За аналогією з Хелм - Холм, Пшемишль - Перемишль. Як ваша думка?

**Comment by OnaHe** [comment]
До речі, як щодо того, аби додати "Перемиський"/"Перемиській" тощо з позначкою не за чинним правописом?

**Comment by arysin** [comment]
силовик, БТРи додав
щодо інших треба порадитись

**Comment by vstarko** [comment]
Білгород - вже є в словнику. Таганріг - в старіших текстах трапляється (можна подати з тегом :rare), Берестя - вже є в словнику, перемиський - вже є в словнику.
Подавати Бєлгород тощо як небажані не варто.

**Comment by OnaHe** [comment]
перемиський нема, як я бачу на r2u. Таганріг можна дати як "не за чинним".

**Comment by arysin** [comment]
дякую, додав перемиський та Таганріг, як «не за чинним», незабаром буде на сторінці

**Comment by OnaHe** [comment]
дякую вам

2017-07-07 5:53 GMT+03:00 arysin <notifications@github.com>:
