### ISSUE TITLE
Відсутні слова не за чинним правописом, синоніми тощо

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#136]
Вітаю.

Додайте не за чинним правописом "рекляма" і решту похідних, слово "можність" як синонім до "можливість", "Преміюм-підтримка" (не за чинним), нагадувальник. 
Поки все.

**Comment by OnaHe** [comment]
також, "мощення"

**Comment by arysin** [comment]
дякую, додано
