### ISSUE TITLE
Відсутнє слово

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#139]
Вітаю
Додайте "асасин" і похідні

**Comment by OnaHe** [comment]
дож

**Comment by OnaHe** [comment]
дож

**Comment by arysin** [comment]
дякую, асасин додамо, а от похідних щось у текстах не знайшов

**Comment by OnaHe** [comment]
ще "Вінничині" не помилкове зробіть, а не за чинним ;)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Вірусів
немає. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-16 6:00 GMT+03:00 arysin <notifications@github.com>:

**Comment by arysin** [comment]
А чому саме Винничина «не за чинним»? Як на мене типова орфографічна помилка.

**Comment by OnaHe** [comment]
Саме "Вінничина". Пригадую так було на СТБ кілька разів, а потім глянув на
r2u і цілком упевнився. Ось посилання:
https://r2u.org.ua/s?w=%D0%92%D1%96%D0%BD%D0%BD%D0%B8%D1%87%D0%B8%D0%BD%D0%B0&scope=all&dicts=all&highlight=on

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Вірусів
немає. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-19 21:41 GMT+03:00 arysin <notifications@github.com>:

**Comment by OnaHe** [comment]
А ще таке питання.

Побачив слово "діджей" - не за чинним правописом (до речі, варто й "диджей" теж додати як не за чинним), а як правильно тоді?

**Comment by burunduk** [comment]
Якщо не проти, то прошу розглянути такі слова:
carpaccio - Карпачо (Страва, згідно wki)
Succubus - Сукуб (Міфічна істота, згідно wki)
Tengu - Тенґу (Міфічна істота, згідно wki)
Chelicerae - Хеліцери (Частина організму. Анатомія членистоногих, wiki)
Lich - Ліч (Міфічна істота, нежить, wiki)
Kobold - Кобольд (Міфічна істота, згідно wki)
Shuriken - Сюрикен (японська метальна зброя, згідно wki)
Kusarigama - Кусарігама (традиційна японська холодна зброя, згідно wki)

**Comment by OnaHe** [comment]
За аналогією, має бути "кусаріґама"

26 жовт. 2017 р. 21:27 "Olexandr Nesterenko" <notifications@github.com>
пише:

**Comment by OnaHe** [comment]
ще є старі назви українських міст (декомунізовані). От "Дніпропетровськ,
Красноармійськ" тощо. Дніпродзержинськ уже позначене як нерекомендоване,
але решта - ні. Додасте?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Вірусів
немає. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

26 жовтня 2017 р. о 23:00 OnaHe <oglaignaheireann@gmail.com> написав:

**Comment by OnaHe** [comment]
плюс, нема слова "гавбиця", треба додати

27 жовтня 2017 р. о 11:19 OnaHe <oglaignaheireann@gmail.com> написав:

**Comment by OnaHe** [comment]
і також "переважальний"

1 листопада 2017 р. о 16:01 OnaHe <oglaignaheireann@gmail.com> написав:

**Comment by arysin** [comment]
Вінничину, гієноподібний, (не)комунікабельний і гавбиця додав.
Диджей, теоретично, має бути правильним (диск + джокей)

**Comment by arysin** [comment]
Додав нове правило для перейменованих нас. п., щоправда там багато ньюансів, тож воно працює переважно для великих міст, де немає омонімії.
Також додав «переважальний»

**Comment by arysin** [comment]
Щодо японських назв, то я вважаю не варто їх додавати, надто вони специфічні.

**Comment by OnaHe** [comment]
Дякую, пане :)

14 лист. 2017 р. 15:20 "arysin" <notifications@github.com> пише:
