### ISSUE TITLE
Додати кілька відсутніх слів

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#144]
Вітаю

Додайте, будь ласка, ці слова:
Дільтай (Дільтей), Ґадамер, Шляєрмахер (Шлеєрмахер), Рікер, тлумачність, екзеґетика, еспериментально-теоретичного, герменевти (герменевтів), постреформаційна, герменевтиках, богонатхненність, Рамбах, Хладеніус, Маєр, природній (дати визначення за не чинним правописом, а не помилкове), взаємобуття, Блас, дивінаторний, фраґмент (дати за не чинним правописом), проінтерпретовано, Дройзен, рекогнітивний, генеричний, пізнавач, життєпрояв, об'єктивування, геґелівський, Гайдеґер, Гайдеґґер, Марбурґ, екзистенційно-феноменогічний, люз, речовність, Гусерль, ґадамерівський, дорефлексивний, допредикативний, Страсбурґ, Чикаґо, феноменолог, позбуття, ієрофанічний, оноричний, зворотній (не за чинним), мовлячий, онтологізація, передструктура, недогматичний, передрозуміння, редукціоністський, історико-психологічний, проблематизація, інтеракціонізм, інтерпретативний, взаємообмеження, самопрояснення, передволодіння, передсхоплювання.

Слів багато, але додав більшість з яких позначило як невідомі (перевіряв курсову).

**Comment by arysin** [comment]
З власними назвами (особливо не дуже частотними) я намагаюся бути консервативним.
екзеґетика - це не за чинним?
еспериментально-теоретичного - тут помилка
герменевтиках - а як воно у множині вживається?
природній - можна дати ':alt'  але воно створюватиме омонімію для місц.в. природний, тому я б радше не давав (так само зворотній)
деякі слова незрозумілі, речовність, мовлячий тощо, передсхоплювання, передволодіння теоретично можливе, але досить рідкісне
решту додам сьогодні, спробуйте завтра на сторінці ще раз прогнати

**Comment by OnaHe** [comment]
екзеґетика - це не за чинним?
так
герменевтиках - а як воно у множині вживається?
герменевтики, якшо я правильно розумію?

слова можуть видаватись незрозумілими, бо то філософія. але такі терміни наявні.

**Comment by bunyk** [comment]
А в мене https://r2u.org.ua/check виділяє помилки при перевірці:

> Наприклад, **Джимбо Вейлз** використав для створення вікіпедії ідею wiki **Ворда Кеннінгема**
> ... від найпершої програмістки на світі Ади **Лавлейс** і робіт Алана **Тюрінга** з штучного інтелекту.

Я б сказав що це частотні власні назви. :) Принаймні я б хотів їх частоту збільшити. :)

**Comment by arysin** [comment]
Так, ми ще систематично не підходили до опрацювання іноземних імен, плюс є хитання і нестандартизованість їх написання, тож це питання не таке просте. А додавати їх по одному це досить довга і невдячна справа. Хоча Тюрінга, Вейлз та Джимбо варто було б додати.
На жаль ми тільки-но випустили версію 4.0.0, тож на деякий час словник заморожено, потрібно підігнати інші частини модуля до випуску LanguageTool 4.0.

**Comment by shvedova** [comment]
аквагрим, Рівнерада, онкохірург, лімфодисекція, соцробітниця, терцентр, абонслужба, Держгеокадастр, сурикат, пуменятко, лактопозитивний, держпродспоживслужба, припляжний, піцейола, етномузей, розтлілий, обожествити, охрещуватись, панкреатопія, фітоаптека

**Comment by shvedova** [comment]
аеророзвідка, млявоплинний, хортинг, союзянка, субсидант, декупаж

**Comment by shvedova** [comment]
вторресурси, верхоплут, набирування, кафасор, затяганка, шабак (вишивка), проолігархічний, депремійований, дрібноцибулевий, квілінг, чипування, симпатяжка, щосесії, демотивувати, бджолозапильний, кіндер, посткросінг, посткросерський, вінтажний, відеорезюме, дактилолог, знелюднення, айдарівець, пронафталінений, рециклер, яйцебаза, перевізницький, експортозалежність, музкерівник
