### ISSUE TITLE
нові слова: криптовалюта тощо

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#148]
додати: скріншот, нікнейм, енергофорум, криптовалюта, криптовалютний
месенджер, чат, контент - це не жаргонні, а вже звичайні слова
аська - жаргонне

**Comment by vstarko** [comment]
додати ще: стримінг, холівар :slang, голівар :slang, оприявнити, оприявнитися, транстихоокеанський, Емманюель, антимексиканський, прогресивізм, техновелетень, техногігант, квазімонополіст, технобізнес, інкременталізм, викаблучування

**Comment by shvedova** [comment]
Декомунізацію вже додали?

**Comment by burunduk** [comment]
Ту нещодавно (2008р) вийшов словник нецензурної лексики. Просто цікаво, її, колись, будуть додавати, як приклад, що то є нецензурщина? (В гугла є такий словник, слова з нього не пропонуються в автодоповнені)

**Comment by arysin** [comment]
> Декомунізацію вже додали?

https://r2u.org.ua/vesum/?w=%D0%B4%D0%B5%D0%BA%D0%BE%D0%BC%D1%83%D0%BD%D1%96%D0%B7%D0%B0%D1%86%D1%96%D1%8F

**Comment by arysin** [comment]
> Тут нещодавно (2008р) вийшов словник нецензурної лексики
Теоретично (принаймні якусь частину нецензурщини) додати можна, але насправді ВЕСУМ позиціюється, як словник для NLP, тобто опрацювання текстів. А у звичайних текстах, що з ними працюють засоби NLP, мабуть, такої лексики досить обмаль. Тож гамузом додавати, думаю, не варто.
Якщо ж у вас є список такої лексики, що дійсно вживають і на ваш погляд варто додати — пишіть, розглянемо.
