### ISSUE TITLE
нові слова: мохіто тощо

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#150]
мохіто, брендований, харизматик, запоребрик :slang, електрокар, електроседан, тюнинг, спайс :slang, каннабіноїд, фентаніл, ескроу, ескроу-агент, незалежницький, радіобирка, народини, геоінженерія, ейджизм, ейджист, сексист, сексистка, сексистський, заскорузліший, Пхьончхан, Азіада, суперняня, юніоністський, некльовий :slang, бритпоп, Меркосур, Гоум-офіс, післяпутінський, ґолліст, ґоллізм, ґоллістський, голліст, голлізм, голлістський, кібервійна, кіберстрахування, криптоджекінг, майнинг, майнити, плагін, криптоінвестор, незалежницький, ретвіт, ретвітнути, твіт, твітнути, Волл-стріт, збалансовування, офлайновий, ультрашвидкісний, стрімінг, стрімінг-сервіс, Голівуд (досить часте написання), голівудський, стрімити, техкомпанія, відеопотоковий, спорттовар, кіберспортивний, Стаффордшир (не завадило б й інші графства додати), підфортунити, підтисковий, переускладнений, Ілон, Маск, брекзит (є також Брекзит, Брекзіт, але найвдаліша форма брекзит), автостатистика, мінівен, доїжджання, меритократичний, тисячолітник, міленіал, мілленіал, аутлет,  індивідуалістичніший, парадигмальний, гадронний, Гугл, Ґуґл, гуглити, ґуґлити, загуглити, заґуґлити, гуглиться, ґуґлиться, загуглений, заґуґлений, кубіт, квантовик, витанцьовувати, витанцьовування, Таймс :foreign, Лего, ґо (як варіант написання назви гри), східноазійський, безкрихтовий, РНК-інтерферентний, лімфобластичний, непомічний, дітовбивчий, спорозоїт, мерозоїт, надліжковий, невакцинований, співвинахідник, людиноцентричний, вузьконаціоналістичний, рогінджа, нефінансований, рейганівський, відлученість, старожитець, насмішливо, похит, веган, Ньюарк, проречисто, північносхідний, підставово, захмарно, розпробувати, радійник, шмякнути :coll, двіж :slang, спортарена, лаунж, аквазона, кардіотеатр, пілатес, міні-футбольний
ентузіязм, григоріянський, юліянський, Еспанія - :alt

**Comment by arysin** [comment]
мохіто noun:m:nv ?
запоребрик р.в. -у?
тюнинг чи тюнінг?
насмішливо - точно добре? (
https://r2u.org.ua/s?w=%D0%BD%D0%B0%D1%81%D0%BC%D0%B5%D1%88%D0%BB*&scope=all&dicts=all&highlight=on
)



6 січня 2018 р. о 11:00 vstarko <notifications@github.com> написав:

**Comment by arysin** [comment]
Голлівуд має з двома писатися, бо це власна назва, хіба не так?

7 січня 2018 р. о 14:21 Andriy Rysin <arysin@gmail.com> написав:

**Comment by arysin** [comment]
повар, поварський - це ок?
https://www.facebook.com/chystamova/posts/379722262183890


7 січня 2018 р. о 14:36 Andriy Rysin <arysin@gmail.com> написав:

**Comment by arysin** [comment]
Ще питання,
Волл-стріт це noun:f:nv ??
чи відмінюється перша частина в
Пенсильванія-авеню?

що таке
непомічний?

7 січня 2018 р. о 14:41 Andriy Rysin <arysin@gmail.com> написав:

**Comment by vstarko** [comment]
мохіто noun:m:nv ? так
запоребрик р.в. -у? вживають з -а і з -у. -а переважає, вочевидь, з огляду на суфікс (пор. каталізатора, хоча це речовина). За семантикою мало би бути -у. Можна вважати, що закінчення наразі неусталене. Подати обидва або лише -а.
тюнинг чи тюнінг? тюнинг  (але тюнінг можна додати як :bad) - ще варто додати: тюнингувати, тюнингований, затюнингувати, затюнингований, тюнингування
насмішливо - точно добре? ні, це :bad --> насмішкувато, глузливо
Голлівуд має з двома писатися, бо це власна назва, хіба не так? Так, і похідні теж. Однак написання через одну -л- досить поширене. Можна подати Голівуд, голівудський із жорсткою заміною й повідомленням: за чинним правописом правильно Голлівуд і голлівудський (пар. 89.3)
повар, поварський - це ок? Ні, це :bad --> кухар, кухарський, куховарський. 
Волл-стріт це noun:f:nv ? так
чи відмінюється перша частина в Пенсильванія-авеню? ні
що таке непомічний? not helpful, є приклади в мережі

**Comment by burunduk** [comment]
Тетива; алебарда є, алебардника немає.

**Comment by arysin** [comment]
в нас є алебардист, але додамо й алебардника
щодо тетива, то схоже українською тятива

**Comment by burunduk** [comment]
Так, тятива краще. Збило з пантелику, що переважно в словниках тетива також є.
