### ISSUE TITLE
Словник для Mac OS X

### ISSUE THREAD

**Issue by merlin-zaraza** [brown-uk/dict_uk#154]
Чи є можливість згенерувати словник для системи Mac OS X?

**Comment by arysin** [comment]
На жаль не працюю з MacOS X, але ось тут писали, що можна: https://www.facebook.com/rzinchenko/posts/10154381153885803
(хоча нижче коментували й люди в яких так не спрацювало).
Якщо спрацює і потрібен останній словник - пишіть, можна швидко згенерувати останню версію (має 323 тис. лем).

**Comment by merlin-zaraza** [comment]
Дякую

**Comment by arysin** [comment]
нема за що, буду вдячний, якщо відпишете тут або в тій гілці на ФБ чи у вас
вийшло

**Comment by merlin-zaraza** [comment]
Так, вийшло.
