### ISSUE TITLE
нові слова 14.05.2018

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#157]
толерований, оприявнювати/оприявлювати, оприявнюватися/оприявлюватися, оприявнення/оприявлення, унаявнення, унаявнений, розпрацювати, розпрацьований, розпрацювання, металексикографічний, металексикографія, стосилий, настроєво, прилітературний, сподобляти :rare, сподобити :rare, сподобивши :rare, автовиправлення, автовиправляння, безредакторний, фрик, мікроменеджмент, стент, мем, майнер, співдиректорка, Штерберг, штетл, їдишський, їдишомовний, івритомовний, івритський, Хозарія, радзивіллівський, Рєпін, п’ятигривневий, стогривневий, вихрещування, вихрещення, Смірна, талмудист, римо- (у фразі римо- й греко-католицький), водинадцятеро, вдванадцятеро, втринадцятеро, вчотирнадцятеро, вп’ятнадцятеро, вшістнадцятеро, всімнадцятеро, увісімнадцятеро, вдев’ятнадцятеро, удвадцятеро (далі за десятками і за сотнями), сокоморсовий, ребе, гомілетичний, талмуд (це слово є в словнику, але в род.в. одн. повинно мати -у, а не -а), федералізована, неєврейський, підавстрійський, підпольський, шинкарство, слабкорозвинений, Вагилевич (прізвище), Андрей (у сполуці «Андрей Шептицький», можна навіть виправляти хибне «Андрій Шептицький»), поч. (крапкове скорочення від «початок»)

**Comment by arysin** [comment]
Штерберг - можливо Штернберг?
Рєпін - а сполука «рє» - це ок?
Смірна чи Смирна?
римо-катол* вже є
водинадцятеро - всі числівники в словник не заведеш, можливо обмежитися першою десяткою?
Андрей - чи варто додавати, чи не замаскуємо TP?

**Comment by LubomyrIvanitskiy** [comment]
ще будьласка
"стеганографія"
"реплянка" (страва з картоплі і кукурудзи)

**Comment by arysin** [comment]
щось я «реплянка» в українських текстах не знайшов

**Comment by LubomyrIvanitskiy** [comment]
"протиріччя"
"принаймі"
"співпадає"
"огинаюча"
"частоково"
"безпека"
"амигдалин"
"докора"

**Comment by vstarko** [comment]
Штерберг - можливо Штернберг? - так
Рєпін - а сполука «рє» - це ок? - ОК
Смірна чи Смирна? - і те, і те є в текстах
водинадцятеро - всі числівники в словник не заведеш, можливо обмежитися першою десяткою? - першої десятки замало. Треба заводити ті, що є в текстах, а в текстах вживаються до першої двадцятки й далі через десяток (втридцятеро, вп’ятдесятеро...)
Андрей - чи варто додавати, чи не замаскуємо TP? - є такий ризик. Тоді варто обмежити "Андрей" сполуками: Андрей Шептицький, митрополит Андрей.
