### ISSUE TITLE
Кілька зауваг по словах

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#165]
Добрий вечір.

Можливо, варто позначати "жреці"/"жреця" як помилкове й виправляти на "жерці"/"жерця"

**Comment by OnaHe** [comment]
додати: "ансамблювати"; "розложення" (?, не впевнений, але може від "розложити");

**Comment by arysin** [comment]
Слова додав, жреці/жреця треба трішки поміркувати, як це зробити найкраще.

**Comment by OnaHe** [comment]
Ще такі слова варто додати:
Пелагіянські, пелагіян (не за чинним);
напередвизначення, топономістичним.

**Comment by vstarko** [comment]
додаймо топонімістичний :bad > топонімічний

**Comment by OnaHe** [comment]
@arysin звертаю увагу й на такі слова:
Пшемисль
Хелм
Жешув

Пропоную їх позначити як помилкові з виправленням на Перемишль, Холм і Ряшів, відповідно.

**Comment by ostasevych** [comment]
> Ще такі слова варто додати:
> Пелагіянські, пелагіян (не за чинним);
уже за чинним :) я пропоную додавати певні гіпертекстові зноски для позначення слів, написання яких відрізняється від чинного правопису з поданням версії згідно з чинним та короткої позначки, напр., іст.(орично), авт.(авторський стиль) тощо.

**Comment by arysin** [comment]
там в новій редакції правопису багато змінилося, тож найпростіше наразі при перевірянні мати два варіанти: старий та новий, окремо

**Comment by OnaHe** [comment]
Додасте "проєкт" замість "проект" і похідні?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Вірусів
немає. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 28 трав. 2019 о 19:00 arysin <notifications@github.com> пише:

**Comment by arysin** [comment]
так, зараз працюємо над підтримкою правопису 2019
