### ISSUE TITLE
Додати відсутні слова

### ISSUE THREAD

**Issue by OnaHe** [brown-uk/dict_uk#168]
Вітаю, можливо варто зробити постійну тему, куди можна додавати слова?

Додати:
Острогозького
Острогозьк

**Comment by arysin** [comment]
Дякую, додам.
Постійну тему не варто, бо потім складно стежити, що вже додано, а що ні.

**Comment by OnaHe** [comment]
А може, це якось спростити і писати напряму вам на ел. скриньку?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Вірусів
немає. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 30 січ. 2019 о 00:15 arysin <notifications@github.com> пише:

**Comment by arysin** [comment]
На скриньку має шанси загубитися — я часто не маю одразу часу додавати, тож треба такі речі однаково кудись складати, github issues, в принципі, для такого й зроблено.

**Comment by OnaHe** [comment]
Можливо вартує подавати "аренда" й похідні як неправильні й виправляти на "оренда" і т.д.?

**Comment by arysin** [comment]
Це залежить від того наскільки часте помилкове написання і наскількі тривіальне виравлення.
Якщо помилка трапляється нечасто або виправлення тривіальне, модуль орфографії її підкреслить і надасть варіант виправлення. Заносити всі можливі помилки в словник досить кропітке заняття.
