### ISSUE TITLE
Підготувати словник для нової редакції правопису

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#169]
Треба продумати, як ми будемо впроваджувати нові норми правопису в словник і LT
Схоже, що новий і старий правопис будуть деякий час співіснувати, тож треба мати стратегію.
Або тримати дві окремі версії словника і правописник, або мати в словнику теги і якісь прапорці для правил.
Підозрюю перший варіант був би простішим для нас (особливо, якщо в якийсь момент можна буде старого варіанту позбутися). З іншого - цей варіант складніший для офіційного LT, а також є проблема тегування текстів, бо тепер тексти будуть за двома правописами (особливо у перехідний період) і тоді тре мати другий варіант.
Тож з практичного боку схоже другий варіант - way to go.

Тоді можливо так:
1) словник матиме два нових теги: spell_1998, spell_2018 - ці теги треба тільки для слів, написання яких змінять
2) LanguageTool матиме два варіанти української uk_UA.1998, uk_UA.2018
3) деякі правила будуть автоматично вмикатися/вимикатися залежно від вибраного варіанту української

**Comment by ostasevych** [comment]
Перепрошую, я нуб у LT: чи можна використати окремий тип позначення варіятивности у написанні слів - підкреслення певним кольором, гіпертекстова позначка принаведенні? Щоб правописник підказував варіяції авторові, а він уже сам вибирав, що саме використати? В такому разі краще буде не тримати окремі варіянти написання, щоб не створювати плутанини.

**Comment by arysin** [comment]
Поки я думаю зробити два варіанти правопису для української, і коли перевіряти можна буде вибрати варіант написання. Опрацьовувати обидва варіанти і давати поради динамічно буде трішки складніше.
Український модуль базується на LanguageTool, який має свою функціональність і додавати щось дуже особливе досить непросто, тож здебільшого намагаємося використати наявний функціонал для українських реалій.

**Comment by arysin** [comment]
Наразі для слів що є лише в одній версії правопису ми додаємо теги `ua_1992` та `ua_2019`
Також в LT є правило, що підсвітлює слова, що мають тег ua_1992.
Орфографічні словнички для Firefox та LibreOffice.org наразі просто містять (тобто дозволяють) й одні й інші форми.
Тримати дві версії мови досить кропітка робота й невідомо чи є потреба перевіряти тексти лише за старим (1992) правописом.
