### ISSUE TITLE
проблеми в наявних парадигмах

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#176]
зобразити /v1.is0.it0 :perf – тут поміняти прапорець it0 на it1, бо має бути не зобрзь, зобразьмо, зобразьте, а зобрази, зобразімо, зобразіть. І ще: не розумію, що тут генерує прапорець is0, бо форми зображено не бачу.
Та сама проблема (хибний прапорець it0): вварити
мжичити – додати також форми мжичив, мжичила, мжичитиме 
передплата - додати множину (різні передплати)

**Comment by vstarko** [comment]
ще проблеми:
бач verb:imperf:impr:s:2 – додати &insert
абияк adv - чи  не треба &pron
чому не абразивний /adj.adv  а двома лемами: абразивний /adj   абразивно adv
блокований /adj :&adjp:pasv:imperf:perf – зняти perf , може додати &&adjp (блокована валюта)
Зореслав /n20.a.p.ke.< - додати .patr?
подув noun - додати парадигму множини
подорожуватися – подати з парадигмою, як до спатися
їхатися – бракує форми їхатиметься
послабнути – там мають бути подвійні форми (послабнула – послабла тощо), як у худнути

**Comment by arysin** [comment]
абразивний adj та adv можна разом і окремо, краще разом, але інколи вони
мають додаткові теги (або просто історично так склалося, що окремо)
