### ISSUE TITLE
Тегування ініціалів

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#181]
Ініціал П. перед розпізнаним прізвищем утиліта TagText.groovy протегувала так:
П.[П./noun:anim:f:v_dav:nv:np:prop:fname:abbr,П./noun:anim:f:v_kly:nv:np:prop:fname:abbr,П./noun:anim:f:v_mis:nv:np:prop:fname:abbr,П./noun:anim:f:v_naz:nv:np:prop:fname:abbr,П./noun:anim:f:v_oru:nv:np:prop:fname:abbr,П./noun:anim:f:v_rod:nv:np:prop:fname:abbr,П./noun:anim:f:v_zna:nv:np:prop:fname:abbr,П./noun:anim:m:v_naz:prop:fname:abbr]
Чому до ч.р. подано лише наз.в., а до ж.р. всі відмінки?

**Comment by arysin** [comment]
Тому що, скоріш за все, наступне прізвище має ч.р. відмінюваний, а ж.р. — ні. Напр. для П.Порошенко, П. отримає н.в.ч.р. та всі відмінки для ж.р.

**Comment by vstarko** [comment]
Гаразд. Тоді виходить, що для чоловічого прізвища й ініціала кличний цілком ігноруємо, а для жіночого прізвища й ініціала кличний подаємо як варіанти.

**Comment by arysin** [comment]
Є така вада, можна або прибрати к.в. з ж.р., або вже одразу виправити #84

**Comment by vstarko** [comment]
прибирати не варто. Краще виправити #84

**Comment by arysin** [comment]
#84 виправлено
