### ISSUE TITLE
Опис формату даних

### ISSUE THREAD

**Issue by olegmisar** [brown-uk/dict_uk#182]
Файл `dict_corp_lt.txt` генерується у форматі
```
слово початкова_форма властивості:розділені:двокрапками
```
Чи є десь опис `властивостей:розділених:двокрапками` для всіх частин мови?

Щось приблизно таке:
```
noun:
    anim | inanim - істота чи не істота
    v_naz | v_rod | ... | v_kly - відмінок
```

Деякі властивості зрозумілі зразу, але інші - ні, наприклад:
```
noun:
    m | f | n | p - це може бути masculine | feminine | neuter | plural, але я не впевнений
```

Винесення опису вихідних даних в `README.md` або в сторінку на Wiki допомогло б користувачам легше використовувати дані словника.

**Comment by olegmisar** [comment]
Ах, погано шукав. Не помітив папки `doc`. Можна додати посилання на опис тегів в `README.md`, щоб не було таких ситуацій в майбутньому.

**Comment by arysin** [comment]
Дякую, додав посилання на doc/ в README.md
