### ISSUE TITLE
тхір має бути anim

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#184]
тхір, недоросток, сприймач мають бути anim

**Comment by mshvedova** [comment]
Також має бути anim закуп

**Comment by arysin** [comment]
> Також має бути anim закуп
@mshvedova  закуп — це закупівля, чому anim?

**Comment by mshvedova** [comment]
книгар
забруднювач
горностай
болван
абрек
чашник
укріплювач
тверезник
сиґналізатор
сигналізатор
припутень
примітив
повторювач
палатин
назимок
крижень
кочет
комунікатор
зав
ембріон
експорт-фактор
дук
далекогляд
військком
вулканізатор
бурхан
баранчик
анчоус
акин

**Comment by mshvedova** [comment]
+

ігрисько має тег m замість n

**Comment by mshvedova** [comment]
ембріон, можливо, не помилка, там м.б. варіативність

**Comment by mshvedova** [comment]
худопахолок (anim)
фактор (м. б. anim)
субститут (м. б. anim)
старичок 
спричинник
спальник
продуцент

+Немає слова пушка

**Comment by arysin** [comment]
Коментарі від @mshvedova

книгар
забруднювач
горностай
болван
абрек
чашник
укріплювач
тверезник
сиґналізатор
сигналізатор
припутень
примітив
повторювач
палатин
назимок
крижень
кочет
комунікатор
зав
ембріон
експорт-фактор
дук
далекогляд
військком
вулканізатор
бурхан
баранчик
анчоус
акин

ігрисько має тег m замість n

ембріон, можливо, не помилка, там м.б. варіативність

худопахолок (anim)
фактор (м. б. anim)
субститут (м. б. anim)
старичок
спричинник
спальник
продуцент

+Немає слова пушка

**Comment by arysin** [comment]
Не бачу вжитку anim для
сигналізатор
кочет
комунікатор
ембріон
далекогляд

решту виправив, дякую
