### ISSUE TITLE
додати @ (другий знахідний) до низки слів

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#187]
Частотний список лем, які мають форми другого знахідного >10 разів у ГРАКові й не мають @ у ВЕСУМі:
язик| 1,683
меч| 743
палець| 609
м'яч| 373
сірник| 341
хрест| 307
вірш| 291
кашкет| 288
плащ| 244
вітер| 224
папірець| 216
пістолет| 211
рукав| 204
пістоль| 183
кошик| 178
конверт| 177
картуз| 169
револьвер| 168
чуб| 167
гаманець| 167
облизень| 166
кожух| 158
бланк| 157
ліхтарик| 154
олівець| 151
сапфір| 144
гопак| 138
ліхтар| 137
рушник| 122
ґудзик| 118
гріх| 114
плуг| 112
квиток| 112
келих| 107
бриль| 105
зошит| 102
щоденник| 100
дзьоб| 98
піджак| 96
кухоль| 95
кулак| 90
люк| 88
записник| 88
живіт| 83
світ| 82
двигун| 81
батіг| 81
літак| 78
портфель| 77
перстень| 77
автомат| 77
прочухан| 76
мішок| 75
карбованець| 74
хропак| 72
носик| 70
камінь| 70
шолом| 65
кулемет| 62
смолоскип| 60
міх| 60
акт| 60
вечір| 59
каганець| 58
бінокль| 57
поріг| 56
телевізор| 54
черевик| 53
кавун| 53
халат| 52
стовп| 52
глек| 52
візок| 52
щит| 51
кіш| 51
пензель| 50
млин| 50
ножик| 49
корабель| 49
кинджал| 49
чайник| 48
драпак| 48
наган| 47
мотор| 47
вузлик| 47
светр| 46
дрючок| 46
горщик| 46
Борок| 46
стусан| 45
пояс| 45
номер| 44
ланцюг| 43
гачок| 43
хребет| 42
пліт| 41
пиріг| 41
носовичок| 40
корж| 40
кийок| 40
капелюшок| 40
віник| 40
паспорт| 39
комір| 39
віршик| 39
блокнот| 39
мобільник| 38
копняк| 38
глечик| 38
костур| 37
камінець| 37
недопалок| 36
хрестик| 35
пакет| 35
наплічник| 35
міст| 35
каптур| 35
замок| 35
тягар| 34
тропак| 34
кий| 34
вимикач| 34
аркуш| 34
шнур| 33
циліндр| 33
цвях| 33
телефон| 33
писок| 33
гребінець| 33
бук| 33
автомобіль| 33
кисет| 32
руль| 31
лот| 31
бублик| 31
чобіт| 30
череп| 30
мотуз| 30
кріс| 30
керн| 30
документ| 30
горб| 30
предмет| 29
поїзд| 29
п'ятак| 29
вітряк| 29
автобус| 29
ящик| 28
червінець| 28
фартух| 28
топ| 28
танк| 27
словник| 27
пам'ятник| 27
карабін| 27
дзвоник| 27
потиличник| 26
мушкет| 26
гудзик| 26
грубер| 26
світильник| 25
ремінь| 25
підручник| 25
пуп| 25
молоток| 25
лікоть| 25
псалтир| 24
пас| 24
нагай| 24
білет| 24
ґніт| 23
прутень| 23
остюк| 23
орден| 23
об'єкт| 23
жертівник| 23
гріш| 23
термін| 22
мізинець| 22
магнітофон| 22
комп'ютер| 22
кожушок| 22
вінок| 22
будильник| 22
арбалет| 22
ріг| 21
макогін| 21
ключик| 21
берет| 21
язичок| 20
сніп| 20
рівень| 20
рюкзак| 20
рецепт| 20
пароплав| 20
нотатник| 20
носовик| 20
шпиль| 20
фок| 19
пеньок| 19
папір| 19
недокурок| 19
мікрофон| 19
монастир| 19
круг| 19
килим| 19
дзвін| 19
вогник| 19
апарат| 19
ротик| 18
пакунок| 18
кухлик| 18
ковчег| 18
держак| 18
ціп| 17
рубль| 17
подарунок| 17
налигач| 17
мундир| 17
м'ячик| 17
кінчик| 17
запобіжник| 17
дрюк| 17
вузол| 17
вугіль| 17
букет| 17
блок| 17
баян| 17
багнет| 17
якір| 16
штурхан| 16
чан| 16
холодильник| 16
транзистор| 16
стільчик| 16
самовар| 16
ровер| 16
потяг| 16
млинок| 16
листочок| 16
ланцюжок| 16
лантух| 16
клинок| 16
аркан| 16
Берн| 16
хутір| 15
хвостик| 15
торт| 15
стовбур| 15
мессер| 15
комірець| 15
ковбик| 15
камінчик| 15
дідух| 15
ярлик| 14
шльопанець| 14
тесак| 14
ремінець| 14
прикметник| 14
пензлик| 14
ордер| 14
костюм| 14
корч| 14
коржик| 14
дубець| 14
диплом| 14
горіх| 14
гарпун| 14
важіль| 14
бутель| 14
Павлиш| 14
чемодан| 13
хобот| 13
таляр| 13
сухар| 13
синець| 13
рій| 13
прут| 13
примус| 13
невід| 13
кущ| 13
корінь| 13
капшук| 13
вагон| 13
бот| 13
азимут| 13
автограф| 13
шприц| 12
френч| 12
трос| 12
слоїк| 12
свічник| 12
радіоприймач| 12
помідор| 12
плід| 12
пиріжок| 12
перстеник| 12
огірок| 12
маузер| 12
листок| 12
кунтуш| 12
косяк| 12
клин| 12
запоясник| 12
дукат| 12
дропак| 12
вареник| 12
букер| 12
брилик| 12
багажник| 12
аркушик| 12
шнурок| 11
черевичок| 11
тотем| 11
тиждень| 11
сюртук| 11
стяг| 11
сенсор| 11
прищ| 11
парабелум| 11
пальчик| 11
очкур| 11
мішечок| 11
мазер| 11
лубок| 11
ківш| 11
кран| 11
корок| 11
запотиличник| 11
грамофон| 11
гвіздок| 11
віночок| 11
вал| 11
болт| 11

**Comment by arysin** [comment]
@vstarko @shvedova
Таке враження, що ці іменники маєть цю форму з.в. лише в деяких випадках (після дієслів??)
Бо наприклад "знайти телефона" ок, але "через телефона" (де "через" вимагає з.в.) не пасує.
Чи є сенс лише додавати ці відмінки після (перехідних) дієслів?

**Comment by arysin** [comment]
@vstarko @shvedova
Почитав [статтю Марії](http://linguistics.kspu.edu/webfm_send/2218), схоже таки з прийменниками теж може бути
