### ISSUE TITLE
додати другий знахідний множини для noun:anim

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#188]
Ми вже маємо його в окремих випадках, наприклад, корови noun:anim:p:v_zna. Так само для кінь, вівця.
Треба додати для:
академік 
актор
актриса
апостол
аристократ
артист
президент (іти в президенти)
гість (заходити в гості)
солдат (іти в солдати)
депутат (іти в депутати)
нардеп (іти в нардепи)
заручник (взяти в заручники)
мер (балотуватися в мери)
дурень (пошити в дурні)
лідер (вивести в лідери)
помічник (взяти когось собі в помічники)
москаль (забрати в москалі)
майстер (кандидат у майстри спорту)
людина (вийти в люди)
кандидат (висунути в кандидати)
керівник
учитель
ченець
монах
отаман
начальник
козак
спільник
спільниця
Є також купа одиничних вживань: йти/взяти в гайдамаки, учні, офіціантки, упівці, стрільці, компаньйон, син, самурай, донор, коханка, попихач, кочегар тощо.
Більше таких слів видно в [ГРАКові](http://www.parasolcorpus.org/bonito/run.cgi/sortx?q=aword%2C%5Bword%3D%22%D0%B2%22%5D+%5Btag%3D%22noun%3Aanim%3Ap%3Av_naz%22%5D&q=sword%2Fi+1%3E0~3%3E0;corpname=grac4&attrs=word&ctxattrs=word&structs=doc&refs=%3Ddoc.author%2C%3Ddoc.translator%2C%3Ddoc.title%2C%3Ddoc.date%2C%3Ddoc.original%2C%3Ddoc.genre%2C%3Ddoc.country%2C%3Ddoc.macroregion%2C%3Ddoc.region&pagesize=30&gdexconf=&attr_tooltip=nott;skey=kw;sicase=i).
Теоретично мало не кожна назва професії, виду занять, посади, рангу може мати другий знахідний множини. Треба вирішити, як саме відібрати такі іменники.

**Comment by shvedova** [comment]
І не тільки професії 
++мій сусід подався у наркомани++

**Comment by shvedova** [comment]
У мене вийшло 3200, але тільки чол. рід:

[tag="noun:anim:p:v_naz"&tag!=".*inanim.*"&tag!=".*v_rod.*"] within [tag="verb.*"] [lemma="в" | lemma="у" ] [tag="noun:anim:p:v_naz"&tag!=".*inanim.*"&tag!=".*v_rod.*"]

✓ \| ✗ | \|людина\| | 463 |  
✓ \| ✗ | \|ченець\|чернець\| | 201 |  
✓ \| ✗ | \|солдат\| | 117 |  
✓ \| ✗ | \|козак\| | 114 |  
✓ \| ✗ | \|свідок\| | 81 |  
✓ \| ✗ | \|москаль\| | 80 |  
✓ \| ✗ | \|партизан\| | 75 |  
✓ \| ✗ | \|президент\| | 71 |  
✓ \| ✗ | \|заручник\| | 67 |  
✓ \| ✗ | \|депутат\| | 58 |  
✓ \| ✗ | \|пан\| | 51 |  
✓ \| ✗ | \|повстанець\|повстанка\| | 35 |  
✓ \| ✗ | \|опришок\| | 35 |  
✓ \| ✗ | \|помічник\| | 27 |  
✓ \| ✗ | \|монах\| | 26 |  
✓ \| ✗ | \|бранець\|бранка\| | 26 |  
✓ \| ✗ | \|лицар\| | 25 |  
✓ \| ✗ | \|рекрут\| | 24 |  
✓ \| ✗ | \|піонер\| | 24 |  
✓ \| ✗ | \|доброволець\| | 23 |  
✓ \| ✗ | \|лях\| | 20 |  
✓ \| ✗ | \|гетьман\| | 19 |  
✓ \| ✗ | \|учень\| | 18 |  
✓ \| ✗ | \|лідер\| | 18 |  
✓ \| ✗ | \|пікінер\| | 17 |  
✓ \| ✗ | \|космонавт\| | 17 |  
✓ \| ✗ | \|брати\|брат\| | 17 |  
✓ \| ✗ | \|наймит\| | 16 |  
✓ \| ✗ | \|міністр\| | 15 |  
✓ \| ✗ | \|кандидат\| | 15 |  
✓ \| ✗ | \|герой\| | 15 |  
✓ \| ✗ | \|священик\| | 14 |  
✓ \| ✗ | \|мер\| | 14 |  
✓ \| ✗ | \|товариш\| | 13 |  
✓ \| ✗ | \|розбійник\| | 13 |  
✓ \| ✗ | \|підмайстер\| | 12 |  
✓ \| ✗ | \|спільник\| | 11 |  
✓ \| ✗ | \|радник\| | 11 |  
✓ \| ✗ | \|приймак\| | 11 |  
✓ \| ✗ | \|керівник\| | 11 |  
✓ \| ✗ | \|студент\| | 10 |  
✓ \| ✗ | \|союзник\| | 10 |  
✓ \| ✗ | \|комуніст\| | 10 |  
✓ \| ✗ | \|батько\| | 10 |  
✓ \| ✗ | \|рицар\| | 9 |  
✓ \| ✗ | \|напарник\| | 9 |  
✓ \| ✗ | \|майстер\| | 9
✓ \| ✗ | \|губернатор\| | 9 |  
✓ \| ✗ | \|академік\| | 9 |  
✓ \| ✗ | \|учитель\| | 8 |  
✓ \| ✗ | \|співавтор\| | 8 |  
✓ \| ✗ | \|свинопас\| | 8 |  
✓ \| ✗ | \|пірат\| | 8 |  
✓ \| ✗ | \|офіцер\| | 8 |  
✓ \| ✗ | \|отаман\| | 8 |  
✓ \| ✗ | \|міщанин\| | 8 |  
✓ \| ✗ | \|гусар\| | 8 |  
✓ \| ✗ | \|грек\| | 8 |  
✓ \| ✗ | \|більшовик\| | 8 |  
✓ \| ✗ | \|ромей\| | 7 |  
✓ \| ✗ | \|робітник\| | 7 |  
✓ \| ✗ | \|приятель\| | 7 |  
✓ \| ✗ | \|поліцай\| | 7 |  
✓ \| ✗ | \|полковник\| | 7 |  
✓ \| ✗ | \|моряк\| | 7 |  
✓ \| ✗ | \|льотчик\| | 7 |  
✓ \| ✗ | \|князь\| | 7 |  
✓ \| ✗ | \|дворянин\| | 7 |  
✓ \| ✗ | \|генерал\| | 7 |  
✓ \| ✗ | \|бандит\| | 7 |  
✓ \| ✗ | \|актор\| | 7 |  
✓ \| ✗ | \|штрафник\| | 6 |  
✓ \| ✗ | \|цар\| | 6 |  
✓ \| ✗ | \|сексот\| | 6 |  
✓ \| ✗ | \|пастух\| | 6 |  
✓ \| ✗ | \|ополченець\| | 6 |  
✓ \| ✗ | \|лікар\| | 6 |  
✓ \| ✗ | \|король\| | 6 |  
✓ \| ✗ | \|жрець\| | 6 |  
✓ \| ✗ | \|жених\| | 6 |  
✓ \| ✗ | \|диякон\| | 6 |  
✓ \| ✗ | \|великорос\| | 6 |  
✓ \| ✗ | \|яничар\| | 5 |  
✓ \| ✗ | \|шпигун\| | 5 |  
✓ \| ✗ | \|холоп\| | 5 |  
✓ \| ✗ | \|танкіст\| | 5 |  
✓ \| ✗ | \|суперник\| | 5 |  
✓ \| ✗ | \|солдатик\| | 5 |  
✓ \| ✗ | \|революціонер\| | 5 |  
✓ \| ✗ | \|парубок\| | 5 |  
✓ \| ✗ | \|куркуль\| | 5 |  
✓ \| ✗ | \|коханець\|коханка\| | 5 |  
✓ \| ✗ | \|комірник\| | 5 |  
✓ \| ✗ | \|компаньйон\| | 5 |  
✓ \| ✗ | \|католик\| | 5 |  
✓ \| ✗ | \|капітан\| | 5
і т. д.

**Comment by arysin** [comment]
Ми додали ці форми як noun:anim:p:v_zna:rare, буде в наступній версії
