### ISSUE TITLE
додати :np до абревіатур від власних назв і деяких загальних

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#197]
ДАК noun:f:nv – до цієї й багатьох інших абревіатур слід додати прапорець :np, адже їх (майже) ніколи не вживають у множині. Це стосується абревіатур від власних назв і не стосується абревіатур від загальних назв (наприклад, «різні ЗОШ» - нормальний вжиток). Однак навіть серед останніх є такі, що потребують :np, приміром ЗПГ noun:m:nv # Зріджений природний газ.

**Comment by arysin** [comment]
Ті, що мають тег ':prop' автоматично отримують ':np', тобто тут хіба що додати np до ЗПГ

**Comment by vstarko** [comment]
Бачу. Залишається лише ЗПГ.
