### ISSUE TITLE
не виводити :np та :nv серед граматичних тегів при тегуванні

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#198]
Алеко /<m – дає на виході: Алеко noun:anim:m:v_naz:nv:np:prop:fname – тут прапорці :np та :nv є насправді не граматичними тегами, а прапорцями словозміни. Тобто вони належать до того самого класу, що й n20, n2adj тощо. Цими прапорцями ми задаємо словозміну, а не описуємо граматичні ознаки конкретних словоформ. Тому я вважаю, що, так само як n20 й n2adj, прапорці :np та :nv не варто виводити у веб-інтерфейс і в протегований корпус.

**Comment by arysin** [comment]
`:nv` густо використовується в правилах і динамічному тегуванні, але `:np` можна спробувати прибрати
