### ISSUE TITLE
зайві рядки в парадигмах присвійних займенників його, її

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#207]
оцих не має бути:
його:
 його adj:f:v_naz:nv:&pron:pos
  його adj:f:v_rod:nv:&pron:pos
  його adj:f:v_dav:nv:&pron:pos
  його adj:f:v_zna:nv:&pron:pos
  його adj:f:v_oru:nv:&pron:pos
  його adj:f:v_mis:nv:&pron:pos
її:
її adj:m:v_rod:nv:&pron:pos
  її adj:m:v_dav:nv:&pron:pos
  її adj:m:v_zna:nv:&pron:pos
  її adj:m:v_oru:nv:&pron:pos
  її adj:m:v_mis:nv:&pron:pos
  її adj:n:v_naz:nv:&pron:pos
  її adj:n:v_rod:nv:&pron:pos
  її adj:n:v_dav:nv:&pron:pos
  її adj:n:v_zna:nv:&pron:pos
  її adj:n:v_oru:nv:&pron:pos
  її adj:n:v_mis:nv:&pron:pos

**Comment by arysin** [comment]
Василю, а можеш обґрунтувати? Я не зовсім розумію чому.

сб, 6 лип. 2019 о 10:10 vstarko <notifications@github.com> пише:

**Comment by vstarko** [comment]
_його_ може стосуватися лише об'єкта чол. і сер. роду, а _її_ — лише об'єкта жін. роду: _друг - його книжка, озеро - його береги, сестра - її книжка__.

**Comment by arysin** [comment]
але в цих прикладах його буде noun:v_rod/v_zna:&pron
якщо ми вживаємо його як adj то воно узгоджується з наступним іменником: його (яка) книжка?

**Comment by vstarko** [comment]
ОК, хай буде.
