### ISSUE TITLE
Автоматичне оновлення словника для LibreOffice

### ISSUE THREAD

**Issue by burunduk** [brown-uk/dict_uk#210]
Словник для libreoffice не оновлюється з серпня 2018р.
Натомість є файл `dict_uk/distr/openoffice.org/service/oxt-update.xml`, за яким libreoffice перевіряє оновлення.
Чи можливо автоматизувати правку даного файлу при релізах, чи реліз має бути присутній на серверах extensions.libreoffice.org?

**Comment by arysin** [comment]
Теоретично можна, мабуть, викладати випуски oxt на github і вказати одразу туди. Це буде простіше ніж створювати випуск на extensions.libreoffice.org, але тоді там буде стара версія, тож її теж варто оновлювати.
Наразі основний акцент dict_uk - для вжитку в LanguageTool, бо там окрім орфографії перевіряємо ще й граматику й стиль. Тому випуски словників для LibreOffice.org та Firefox трапляються не на кожний випуск. Але вже пройшло достатньо часу, я оновлю.

**Comment by burunduk** [comment]
Дякую!
А словник синонимів використовується лише в libreoffice?

**Comment by arysin** [comment]
Я оновив словник для LibreOffice.org
Так, наразі словник синонімів використовується лише в LO
