### ISSUE TITLE
Новий правопис

### ISSUE THREAD

**Issue by Jucker7** [brown-uk/dict_uk#211]
Доброго дня, панове.
Перепрошую за незручне питання.
На сторінці https://extensions.libreoffice.org/extensions/ukrainian-spelling-dictionary-and-thesaurus зазначено, що ваш словник вже підтримує новий український правопис (якщо я, звісно, все зрозумів вірно). Але чомусь він не працює після встановлення.
Наприклад, слово "проєкт" він розпізнає як помилкове.
Можливо я десь помилився... Буду дуже вдячний за допомогу. 

LibreOffice 6.0.7.3 (Linux Mint 19.2)

**Comment by arysin** [comment]
Вітання, перепрошую за затримку. Є така проблема, спробуємо невдовзі виправити.

**Comment by arysin** [comment]
Виправив проблему в 4.6.3, спробуйте, будь ласка.
