### ISSUE TITLE
ПІБ (200к+)

### ISSUE THREAD

**Issue by velmyshanovnyi** [brown-uk/dict_uk#213]
Імена 9к / побатькові 16к / прізвища 190к - все лежить готове з 2016 року і чекає поки його візьмуть в роботу...

**Comment by velmyshanovnyi** [comment]
https://github.com/velmyshanovnyi/ua-gazetteers/blob/master/k16_v4_kyiv_name2_unic_9k_imen.rar

https://github.com/velmyshanovnyi/ua-gazetteers/blob/master/k16_v4_kyiv_name2_unic_16k_pobatkovi.rar

https://github.com/velmyshanovnyi/ua-gazetteers/blob/master/k16_v4_kyiv_name2_unic_190k_prizv.rar

3 роки вже лежить....
про пуллрексвест всі забули ))

**Comment by velmyshanovnyi** [comment]
я зараз опрацьовую (в напівручному режимі)
озвучку ГОЛОСОМ 9к імен (для початку)
на  https://uk.forvo.com/user/velmyshanovnyi

цікаво було б спробувати зробити інтеграцію голосового вимовлення для словника )))
...але треба ще трішки "прокачатись" в механіці озвучки,
і придумати максимальну автоматизацію процесу...

я так думаю, що 300к слів реально озвучити одній людині за 3...4 місяці роботи
2...3 місяці за умови роботи в режимі хакатону - ЛИШЕ начитка+сон

**Comment by burunduk** [comment]
А якщо взяти синтезатор, на кшталт rhvoice,  і заставити словником правильно вимовдяти імена? З озвучкою буде простіше. Тим паче він (синтезатор) і інтонаціі вміє міняти.

П.С. переіменуйте, будь ласка, тему. І весь текст, що в назві теми, в опис перемістити.

**Comment by velmyshanovnyi** [comment]
>> А якщо взяти синтезатор, на кшталт rhvoice, і заставити словником правильно вимовдяти імена? З озвучкою буде простіше. Тим паче він (синтезатор) і інтонаціі вміє міняти.

ідея - мати озвучку від НОСІЇВ мови

**Comment by arysin** [comment]
> https://github.com/velmyshanovnyi/ua-gazetteers/blob/master/k16_v4_kyiv_name2_unic_9k_imen.rar
Дякую, я глянув цей файл — з десь 8 тис. імен у нас немає лише пару десятків, незабаром додам...

**Comment by arysin** [comment]
У архіві з по батькові нових для словника немає.
Прізвища не зміг перетворити в Unicode - схоже поламане кодування

**Comment by burunduk** [comment]
А автоматично з імені немає можливоств створювати побатькові?

**Comment by vstarko** [comment]
Ось цей самий список прізвищ в UTF.
[k16_v4_kyiv_name2_unic_190k_prizv(UTF).zip](https://github.com/brown-uk/dict_uk/files/3765978/k16_v4_kyiv_name2_unic_190k_prizv.UTF.zip)

**Comment by arysin** [comment]
> А автоматично з імені немає можливоств створювати побатькові?
Так, прізвища в словнику генеруються автоматично з імен (але треба проставити відповідний прапорець).

**Comment by arysin** [comment]
> 
> 
> Ось цей самий список прізвищ в UTF.
> [k16_v4_kyiv_name2_unic_190k_prizv(UTF).zip](https://github.com/brown-uk/dict_uk/files/3765978/k16_v4_kyiv_name2_unic_190k_prizv.UTF.zip)
Дякую, Василю!
