### ISSUE TITLE
озвучка слів dict_uk на FORVO

### ISSUE THREAD

**Issue by velmyshanovnyi** [brown-uk/dict_uk#216]
починаючи з версії 4.7.0 внесені всі 300к слів словника на озвучку в рамках цього проекту

**запит на конкретне слово** можна отримати так:
https://uk.forvo.com/word/приклад/#uk
(де "приклад" замінити потрібним словом)

**перегляд словника по тегу** "dict_uk" за абеткою тут: 
https://uk.forvo.com/tag/dict_uk/alphabetically/
є проблемка з тим що поки що нема можливості відфільтревати слова, які мають однакове написання, і читаються в різних моваг по різному.

- чому я тут про це написав?
- можливо якомусь з проектів хто користується словником, потрібна озвучка. так от вона вже частково є. і краще хай люди зробять щось інше корисне ніж будуть повторно витрачати час на вже зроблене.

![image](https://user-images.githubusercontent.com/1027826/68546915-865ead80-03e4-11ea-879a-cfe916b1d3d1.png)

там же можна і завантажити вимови по конкретному голосу диктора.
або озвучити самому, якщо потрібна вимова відсутня чи не підходить з якихось причин (акцент/тембр/стать/тощо)

**Comment by arysin** [comment]
Супер, але це не є відкрите питання до dict_uk, тож я його закрию (має все одно шукатися).
