### ISSUE TITLE
додати форму простирадл

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#217]
як паралельну форму род.в. множини до простирадло

**Comment by arysin** [comment]
У нас вже є «простирадл noun:inanim:p:v_rod»:
https://r2u.org.ua/vesum/?w=%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%B8%D1%80%D0%B0%D0%B4%D0%BB%D0%BE

**Comment by vstarko** [comment]
Ет, мав на увазі форму простирадел. Вживається - видно в [ГРАКу](http://www.parasolcorpus.org/bonito/run.cgi/first?corpname=grac7&reload=&iquery=&queryselector=wordrow&lemma=&phrase=&word=%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%B8%D1%80%D0%B0%D0%B4%D0%B5%D0%BB&char=&cql=&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&usesubcorp=&fsca_doc.author=&fsca_doc.translator=&fsca_doc.authTrans=&fsca_doc.born=&fsca_doc.title=&fsca_doc.date=&fsca_doc.mediaName=&fsca_doc.locCode=&fsca_doc.region=&fsca_doc.publicationCity=&fsca_doc.publisher=&fsca_doc.publication=&fsca_doc.uri=).
