### ISSUE TITLE
Chrome: оновити словник вручну

### ISSUE THREAD

**Issue by burunduk** [brown-uk/dict_uk#219]
Запит на оновлення словника в Chromium висить вже більше року і не рухається.
https://bugs.chromium.org/p/chromium/issues/detail?id=913536

Як згенерувати bdic файли з наявного проекту для оновлення вручну?

**Comment by arysin** [comment]
Це треба згадати :), я спробую днями відновити інструкції та викладу їх десь на загал.

**Comment by burunduk** [comment]
Пишуть, що треба зібрати: https://chromium.googlesource.com/chromium/src/+/refs/heads/master/chrome/tools/convert_dict/convert_dict.cc
Але як то зробити без збирання всього проєкту я не розібрався :(

**Comment by arysin** [comment]
Я додав [інструкції](https://github.com/brown-uk/dict_uk/tree/master/distr/chromium) (з оф. випуску і з розробницької версії)

**Comment by burunduk** [comment]
Дякую!
