### ISSUE TITLE
неправильна заміна для водоємкість

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#220]
![image](https://user-images.githubusercontent.com/8600477/71933412-b8a14700-31aa-11ea-955b-bff0abfa7292.png)

**Comment by burunduk** [comment]
теплоємність, ємність конденсатора, питома ємність батареї. Пише, що це помилки. Поправте мене, якщо це дійсно так.

**Comment by vstarko** [comment]
Тут ми спираємося на думку фахівців, зокрема на "Англійсько-українсько-англійський словник наукової мови (фізика та споріднені науки)" (2010, О. Кочерга, Є. Мейнарович), де відповідні терміни з "місткість" наведено першими як рекомендовані, а терміни з "ємність" подано у дужках на другому місці як нерекомендовані до вжитку, але поширені. Ось [приклад](https://e2u.org.ua/s?w=%D1%82%D0%B5%D0%BF%D0%BB%D0%BE*%D0%BC*%D1%96%D1%81%D1%82%D1%8C&dicts=4&highlight=on&filter_lines=on). Можливо, варто всі такі випадки позначати не як помилки (жорстке виправлення), а як нерекомендовані (м'яке виправлення).

**Comment by arysin** [comment]
Наразі, як жорсткі помилки на -ємність у нас лише такі:
газоємність
наукоємність
трудоємність
фотоємність
