### ISSUE TITLE
додати заміни в словник

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#222]
Жорсткі заміни:
відзивний #> відкличний
холоднокатаний #> холодновальцьований
хлебнути #> сьорбнути; зазнати (горя)
хлебтати #> сьорбати; зазнавати (горя)
бугор #> горб, згірок
бугристий #> горбистий, горбкуватий
буйство #> буяння
буйствовати #> буянити, буяти, бушувати
великодушничати #> розводити великодушність
вівцевод #> вівчар
впаювати #> влютовувати
дебоширсто #> бешкетування, бешкетництво, галабурда
жорстокосердність #> жорстокість, немилосердність, безсердечність
жорстокосердно #> жорстоко, немилосердно, безсердечно
зажарювати #> засмажувати
зажарити #> засмажити
зазнаватися #> зарозуміватися, задаватися
зазнатися #> зарозумітися, задатися, запишатися
закупорювання #> закорковування, затикання, зачоповування
закупорення #> закоркування, заткнення, зачопування
закупорений #> закоркований,заткнений, зачопований
закупорювати #> закорковувати, затикати, зачоповувати
закупорити #> закоркувати, заткати, зачопити
зстарити #> постарити
зістаріти #> постаріти
зістарітися #> постаріти
зстаріти #> постаріти
зстарітися #> постаріти
зйомник #> знімач  # додати це слово до наявних варіантів заміни
клятва #> присяга; присягання
дати клятву #> скласти присягу
давати/дати клятвену обіцянку #> заприсягатися, заприсягтися, присягатися, присягтися
клятвопорушення #> кривоприсяга
клятвопорушений #> кривоприсяжний
клятвопорушенник #> кривоприсяжник
клятвопорушниця #> кривоприсяжниця
костиль #> милиця, костур
лунатичний #> сомнамбулічний, сновидний
лунка #> ямка # when not followed by a noun or an adjective
начистоту #> відверто  # додати цей варіант заміни
низькопоклонницький #> низьковклінний, підлесливий, підлабузницький
низькопоклонник #> низьковклінник, підлесник, підлабузник
низькопоклонничати #> низько кланятися, плазувати, підлабузнюватися
низькопоклонство #> низьковклінність, підлесливість, підлабузництво
ниряти #> пірнати
нирнути #> пірнути
обоготворення #> боготворіння
обоготворяти #> боготворити, обожнювати 
обоготворити #> збоготворити, обожнити
обручати #> заручати
обручити #> заручити
окріпнути #> зміцніти, подужчати, поздоровшати 
омертвляти #> змертвляти 
омертвити #> змертвити
опошлити #> звульгаризувати
опошлятися #> вульгаризуватися
опошлитися #> звульгаризуватися
оп’яніти #> сп’яніти
оп’яняти #> сп’яняти
очаровувати #> чарувати, зачаровувати
очарувати #> зачарувати
первоначало #> первопочаток, першооснова
перепаювати #> перелютовувати
перепаювання #> перелютовування, перелютування
переплавлення #> перетоплювання
переплавляння #> перетоплення
переплавляти #> перетоплювати
переплавити #> перетопити
переплавлятися #> перетоплюватися
переплавитися #> перетопитися
переплавний #> перетопний
пересікання #> перетинання
пересікти #> перетнути 
пересіктися #> перетнутися
пересічений #> перетнутий; горбистий (про місцевість)
пересічення #> перетин, перетинання
підвожчик #> підвізник
побагровіти #> побагряніти
подвизатися #> орудувати, працювати (на ниві, полі)
пожаритися #> посмажитися
построїти #> вишикувати
построїтися #> вишикуватися
пощадити #> помилувати, поберегти (почуття тощо), подарувати (життя)
щадити #> милувати, берегти (почуття тощо), дарувати (життя)
пустотілий #> порожнистий
п’яніючий #> що п’яніє; напівп'яний
прокатник #> вальцівник
прокатниця #> вальцівниця
рокотання #> гуркіт, гуркотіння
рокотати #> гуркотіти
рокотіти #> гуркотіти
ротозій #> роззява, ґава
ротозійство #> роззявкуватість, неуважність
слабоумство #> недоумкуватість
строчіння #> стебнування
сутяга #> позивач, позивальник
тугоплавкий #> важкотопний
убавлення #> зменшення
убавляння #> зменшування
убавляти #> зменшувати, знижувати
убавлятися #> меншати, знижуватися 
убавити #> зменшити, знизити
убавитися #> поменшати, знизитися 
угнати #> викрасти
угасання #> згасання, вигасання
угасати #> згасати, вигасати
угаснути #> згаснути, вигаснути
угаслий #> згаслий, вигаслий
угощання #> пригощення, частування
угощати #> пригощати, частувати
угостити #> пригостити, почастувати
угощатися #> пригощатися, частуватися
угоститися #>  пригоститися, почастуватися
угощення #> пригощення, частування
удружити #> зробити послугу, прислужитися
ужарювати #> всмажувати
ужарити #> всмажити
ужарюватися #> всмажуватися
ужаритися #> всмажитися
умножати #> множити
умножатися #> множитися
умножити #> помножити
умножитися #> помножитися
умудряти #> робити мудрішим/мудрим
умудрити #> зробити мудрішим/мудрим
умудрятися #> примудрятися
умудритися #> примудритися
умчати #> помчати
умчатися #> помчатися
фокусничати #> штукарити, показувати фокуси; вередувати
соскоподібний #> пипкоподібний
ханжити #> удавати (з себе) побожного, лицемірити
чекан #> карбівка
чудацтво #> дивацтво
щупальце #> мацак
щупик #> мацак, мацачок
щупання #> мацання
щупати #> мацати
щурити #> мружити, жмурити
щуритися #> мружитися, жмуритися
обезглавлювати #> стинати голову; знечолювати

М'які заміни:
взаємовиключальний #> взаємозаперечний, взаємосуперечливий, несумісний
взаємовиключати #> взаємозаперечувати, взаємосуперечити, бути несумісним
взаємовиключення #> взаємозаперечення, взаємосуперечність, несумісність
взаємовиключний #> взаємозаперечний, взаємосуперечливий, несумісний
взаємовиключність #> взаємозаперечність, взаємосуперечність, несумісність
спай #> злют # додати цей варіант
спаювання #> злютовування
спаювати #> злютовувати
спаяти #> злютувати
спаяний #> злютований
спаяність #> злютованість

**Comment by arysin** [comment]
А як щодо хлебонути?
З лунка складно бо є ще метелик
прокатник - може бути до прокат (оренда?)
строчіння #> стебнування, але ж строчити??
чекан - тут є декілька значень :(

**Comment by vstarko** [comment]
хлебонути #> сьорбанути
А от щодо хлебтати я поспішив - це слово не треба виправляти.
лунка - згоден, хоча метелик (і молюск) набагато рідше трапляються. Але є ще прикметник (лунка хода). Тут треба правило формулювати в LT editor. Можна лише для словоформ множини і для "в/у лунку", "в/у лунці", якщо далі не стоїть іменник чи прикметник.
І ще: треба автоматом знімати омонімію для лунко - це прислівник і майже ніколи не іменник.
прокатник - може бути до кінопрокат ("У сегменті « кіно для душі » українські накопичили кілька прем'єр"). Не правимо.
строчіння - ОК, не правимо 
чекан - точно, не правимо.
