### ISSUE TITLE
некоректний прапорець < до назв надприродних істот

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#226]
Такі назви повинні мати прапорець <>, бо ним позначаємо істоти, які не є людьми. 
Наразі виявив такі:
ангел /n20.a.p.ke.<
ангелик /n20.a.p.ke.<
ангелочок /n22.a.p.<
ангелятко /n2n.p2.ovi.<
ангеляточко /n2n.p2.ovi.<
ельф /n20.a.p.ke.<
агел /n20.a.ke.<
бабай /n20.a.p.<
чорт /n20.a.p.ke.<
чортеня /n40.p.<
домовик /n20.a.p.<
русалка /n10.p2.ko.<
русалонька /n10.p2.ko.<
русалочка /n10.p2.ko.<
мавка /n10.p2.ko.<
Знайшов і назву тварини з таким неправильним тегом:
мавпа /n10.p1.ko.<
В граматичному тегуванні ці відмінності ніяк не впливають на результати (на виході набір тегів не зміниться), однак важливо їх виправити в словнику, щоб можна було приписати правильні семантичні теги.

**Comment by arysin** [comment]
Насправді `<>` ми вживаємо для тварин і цей прапорець додає одну форму: з.в. мн., що збігається з н.в. (гуси, корови тощо).
Ми обговорювали чи варто подавати ці форми для всіх тварин чи лише свійських у #104

**Comment by vstarko** [comment]
Гаразд. Тоді поправити опис тегів, вказавши, що 
< - люди, надприродні істоти
<> - тварини
І виправити тег у мавпи.
