### ISSUE TITLE
додзьо

### ISSUE THREAD

**Issue by int-ua** [brown-uk/dict_uk#238]
https://uk.wikipedia.org/wiki/Додзьо

LanguageTool не знає, а отже, я так гадаю, цього слова бракує у цьому словнику.

**Comment by int-ua** [comment]
і `дан`

**Comment by hedrok** [comment]
Доброго дня! За можливості також додайте варіант "доджьо" (за новішими системами транскрипції). Дякую.

**Comment by arysin** [comment]
@hedrok Я не впевнений, щодо м'якого знаку після «ж», чи не могли б ви навести аргументацію?

**Comment by hedrok** [comment]
@arysin Звісно.

Стисло: за новішими системами (Рубель та Коваленко в статті) じょ передається як "джьо". Це значно ближче до японського звучання. Але це приблизно така сама війна, як Г/Х при передачі англійських імен/назв.

Тому гадав, що додати обидва варіанти слушно: за старішими системами писали "додзьо", за новішими -- "доджьо".

Ну і зізнаюся, що просто моя вчителька японської сильна прибічниця варіантів з "джьо", тому про це пишу.

 Докладна стаття тут: https://uk.wikipedia.org/wiki/%D0%AF%D0%BF%D0%BE%D0%BD%D1%81%D1%8C%D0%BA%D0%BE-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D1%96_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8_%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%86%D1%96%D1%97_%D1%82%D0%B0_%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BB%D1%96%D1%82%D0%B5%D1%80%D0%B0%D1%86%D1%96%D1%97
Там же в статті є "Неузгодженості з правописом", де описано докладно, але в будь-якому разі будь-якою системою передачі японської є неузгодженості з правописом.

Перепрошую за купу тексту.

**Comment by arysin** [comment]
@hedrok Тут проблема з тим, що двозвук [дж] в укр.мові не пом'якшується. Про це можна прочитати в різних підручниках і довідниках з укр.мови. Немає жодного укр. слова з джь.

**Comment by bicolino34** [comment]
@arysin хотів би ще раз підняти питання про транскрипцію з японської мови. Зараз університети радять використовувати системи Ґоджюон або Коваленка за якими буде доджьо. Також ці системи стають дедалі популярнішими не тільки в науковій літературі, але й у перекладах.

На сайті КНУ ім. Шевченка є сторінка з книгами, які були видані їхньою далекосхідною катедрою. Я проглянув японознавчі книги і загалом видно, що новіші книги вже користуються системами з джі, ші, чі, а не дзі, сі, ті. https://philology.knu.ua/struktura-if/kafedry/kafedra-dalekoho-skhodu/diyalnist-kaf-mov-lit-dal-skh-pivd-skh-aziyi/

Ґоджюон або подібні (джі, ші, чі):
1. 2020 Методичні рекомендації з дисципліни «ЛІТЕРАТУРА ЯПОНІЇ ХХ-ГО СТОЛІТТЯ»
2. 2020 Вірші японських імператорів та імператриць. Антологія
3. 2016 Жага кохання. Антологія японської жіночої поезії
4. 2013 Стежками Півночі, Мацуо Башьо
5. 2017 Ономатопеїчна система сучасної японської мови
6. 2016 Тематичний словник японської ономатопеїчної лексики
7. 2018 Шінкокін-вака-шю
8. 2020 Японська ієрогліфіка
9. 2017 Японська мова ґендерний аспект
10. 2020 Японська мова Політичний і дипломатичний переклад
11. 2020 Японська проза XIX ст.
12. 2014-2016 Японська література. Курс лекцій
13. 2013 Японська поетика
14. 2012 Японсько-український словник
15. 2023 Саке і хайку
16. 2023 100 кращих хайку
17. 2022 Тачібана Акемі Радощі
18. 2023 Танеда Сантока Пряма дорога
19. 2023 Йосано Акіко Скуйовджене волосся
20. 2023 100 кращих танка
21. 2024 Одзакі Хосай Одноногий горобчик

Поліванівка (дзі, сі, ті):
1. 2002 Антологія хайку 
2. 2004 Антологія японської класичної поезії. Танка, ренґа
3. 2006 Кокін-вака-сю (на сайті КНУ пише кокін-вака-шю)
4. 2012 Лінгвокраїнознавство Японії
5. 2014 Неприкаяні душі Антологія дзен-поезії
6. 2008 По одному віршу ста поетів
7. 2010 Розкоші і злидні японської поезії
8. 2008 Рьокан, Вибрані поезії
9. 2010 Україна і Схід (Колективна монографія)
10. 2010-2011 Японська література. Хрестоматія
11. 2005 Шьо (каліграфія) — на сайті назва ґоджюоном, всередині поліванівка
12. 2011 Японські поети. Біографічний словник

Якась власна система: 
1. 1966 Шаковський І. Hyaku-nin ish-shu (шу, а не шю або сю; жі, а не джі або дзі)

**Comment by vstarko** [comment]
Я проконсультувався з колегою, яка в темі, й підтверджую, що варто вносити в словник слова, транслітеровані за системою Ґоджюон (Бондаренка) й Коваленка. Мета нашого словника — розпізнавати ті форми, які трапляються в текстах. Тож якщо слова, написані за цими системами, достатньо частотні в текстах, варто їх додавати.

**Comment by bicolino34** [comment]
У наступних версіях ГРАКу подібних слів має стати більше, оскільки якраз потрохи займаюся оформленням метаданих до текстів з цими транскрипціями.

**Comment by bicolino34** [comment]
Мабуть, це питання можна закрити раз слово додзьо вже є у словнику, а питання зі словами за новими транскрипціями теж вирішене
