### ISSUE TITLE
Обкраювати, окунисько, пасмочко, ДІУ

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#239]
має бути з малої: обкраювати
окунисько /n20.p /n2n.ovi.p1.< - треба один код: /n2n.p1.ovi.<>
пасмочко /n2n - додати множину: пасмочко /n2n.p2
ДІУ noun:f:nv:np:prop                       # Державна іпотетечна установа - виправити на "іпотечна"

**Comment by arysin** [comment]
А хіба не можна сказати "той окунисько"?

**Comment by vstarko** [comment]
Mea culpa. Окунисько - лише чоловічий рід. Потрібен тільки один код: окунисько /n20.p.<>

**Comment by arysin** [comment]
Але у нас подвійний рід ще мають: пописько, вовчисько, чортисько, і принаймні, вовчисько [вживають](http://www.parasolcorpus.org/bonito/run.cgi/first?corpname=grac8&reload=&iquery=&queryselector=cqlrow&lemma=&phrase=&word=&char=&cql=%5Bword%3D%22%D0%B2%D0%BE%D0%B2%D1%87%D0%B8%D1%81%D1%8C%D0%BA.*%22%5D&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&usesubcorp=&fsca_doc.author=&fsca_doc.translator=&fsca_doc.authTrans=&fsca_doc.born=&fsca_doc.title=&fsca_doc.date=&fsca_doc.mediaName=&fsca_doc.locCode=&fsca_doc.region=&fsca_doc.publicationCity=&fsca_doc.publisher=&fsca_doc.publication=&fsca_doc.uri=) в обох родах.

**Comment by vstarko** [comment]
В "окунисько" сер. рід теоретично можливий, але практично — навряд. ОК, задля послідовності можна додати йому сер. рід.
