### ISSUE TITLE
Додати: знедіяння

### ISSUE THREAD

**Issue by strixaluco** [brown-uk/dict_uk#244]
У переліку джерел зустрічається саме "знедіяння", але припускаю, що можна додати й похідні (знедіювати, знедіяний тощо)

Джерела:
1. [Н. Куземська. Проблеми культури української мови в проектах національних стандартів України](http://tc.terminology.lp.edu.ua/TK_Work/TK_kuzems'ka_2009_01.htm)
2. [А.І. Липська, Я.І. Серкіз. Природа та закономірності радіаційного канцерогенезу](http://jnpae.kinr.kiev.ua/05.2/Articles_PDF/jnpae-2004-05-2-114.pdf), с.2 [PDF]
3. [Н.А. Михалко. Неоліберальний євгенічний проект у текстах Дж. Агамбена та А. Бадью](https://www.academia.edu/34785548/%D0%9D%D0%95%D0%9E%D0%9B%D0%86%D0%91%D0%95%D0%A0%D0%90%D0%9B%D0%AC%D0%9D%D0%98%D0%99_%D0%84%D0%92%D0%93%D0%95%D0%9D%D0%86%D0%A7%D0%9D%D0%98%D0%99_%D0%9F%D0%A0%D0%9E%D0%95%D0%9A%D0%A2_%D0%A3_%D0%A2%D0%95%D0%9A%D0%A1%D0%A2%D0%90%D0%A5_%D0%94%D0%96._%D0%90%D0%93%D0%90%D0%9C%D0%91%D0%95%D0%9D%D0%90_%D0%A2%D0%90_%D0%90._%D0%91%D0%90%D0%94%D0%AC%D0%AE), с. 2
4. [ДСТУ ІЕС 60335-1:2004](http://gost-snip.su/download/dstu_iec_603351_2004_priladi_pobutovi_ta_analogichni_elektri), с. 24,30,48 [PDF]
5. [А. Ціпко. Гносео-естетична специфікація давньоукраїнської словесності](http://shron1.chtyvo.org.ua/Tsipko_Anatolii/Hnoseo-estetychna_spetsyfikatsiia_davnoukrainskoi_slovesnosti.pdf), с. 509 [PDF]

**Comment by arysin** [comment]
Дякую, додамо

**Comment by strixaluco** [comment]
Прошу і вам дякую. А у народний словник на e2u теж додасте? Чи може краще зробити відповідну тему на форумі?

**Comment by arysin** [comment]
Для e2u краще на форумі.
