### ISSUE TITLE
Додати: нагадка

### ISSUE THREAD

**Issue by strixaluco** [brown-uk/dict_uk#247]
Вбачається слушним додати слово _нагадка_ в якості точнішого віддієслівного іменника, ніж _нагадування_, адже згідно з пунктом Г.5.1.3 **ДСТУ 3699-2009**,

> Віддієслівні іменники на _-ка_ в українській мові означають не процеси, а їхні наслідки, інструменти та об'єкти.

**Приклади вжитку:**
[Грінченко. Словник української мови. r2u](https://r2u.org.ua/s?w=%D0%BD%D0%B0%D0%B3%D0%B0%D0%B4%D0%BA%D0%B0&scope=all&dicts=all&highlight=on)
[ГРАК v9](http://www.parasolcorpus.org/bonito/run.cgi/first?iquery=%D0%BD%D0%B0%D0%B3%D0%B0%D0%B4%D0%BA%D0%B0&corpname=grac9&corpus-search-form=true)

**Comment by arysin** [comment]
дякую, додамо
