### ISSUE TITLE
+m змінює лему на :m

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#25]
До +m:

<pre>
штунда noun:anim:<b>f</b>:v_naz
  штунди noun:anim:f:v_rod
  штунді noun:anim:f:v_dav
  …
</pre>

Після +m:

<pre>
штунда noun:anim:<b>m</b>:v_naz
  штунди noun:anim:m:v_rod
  штунді noun:anim:m:v_dav
  …
  штунда noun:anim:<b>f:v_naz</b>
  штунди noun:anim:f:v_rod
  …
</pre> 

Таким чином втрачається інфа про те, що штундин рідний рід — жіночий.

Очікується:

<pre>
штунда noun:anim:<b>f</b>:v_naz
  штунда noun:anim:<b>m:v_naz</b>
  штунди noun:anim:m:v_rod
  …
  штунди noun:anim:f:v_rod
  штунді noun:anim:f:v_dav
  …
</pre>

**Comment by mariana-scorp** [comment]
Якщо це спільний рід, як жіночий може бути "рідним"?

**Comment by msklvsk** [comment]
Бо парадигма все ж жіноча. Це частника інформації яку просто так викидати не хочеться.

**Comment by arysin** [comment]
Ага є таке, там ми зараз у візуальному словнику не виділяємо жіночу лему окремо (руки не дійшли), для тегувальника в LT такої проблеми не має (бо йому викоремлення лем не потрібно).
Я гляну на це пізніше.

**Comment by arysin** [comment]
Маємо для цього вже #72
