### ISSUE TITLE
Наказова форма дієслів з частками -но, -бо.

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#261]
В українській мові наказовий спосіб дієслів формується також за допомогою часток -но та -бо. Наприклад, говорити -> говори-но, писати -> пиши-бо, слухати -> слухай-но. Можливо, варто навчити ВЕСУМ також генерувати ці словоформи? 

Окрім того, ВЕСУМ не має слів із часткою -то. Наприклад, якби -> якби-то, отакий -> отакий-то.

**Comment by arysin** [comment]
З лінгвістичного боку ці частки є окремими від слова. Тому вносити ці всі варіанти в словник є не зовсім коректним.
Окрім того, аналізатор LanguageTool, який дуже тісно пов'язаний з ВЕСУМ і значно його доповнює, розпізнає й тегує ці випадки динамічно.
Спробувати це можна ось тут https://community.languagetool.org/analysis?lang=uk
