### ISSUE TITLE
Деякі омоніми генеруються як одна лема, а не різні.

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#262]
Деякі омоніми генеруються як одна лема, а не різні. Наприклад, [АПБ](https://r2u.org.ua/vesum/?w=%D0%B0%D0%BF%D0%B1), [АПП](https://r2u.org.ua/vesum/?w=АПП), [АФ](https://r2u.org.ua/vesum/?w=АФ), [ВВ](https://r2u.org.ua/vesum/?w=ВВ&all_forms=on), [ВЗ](https://r2u.org.ua/vesum/?w=ВЗ&all_forms=on) мають два значення, але на виході ці два значення перемішані в одній лемі.

**Comment by arysin** [comment]
Є таке, дякую, гляну.
