### ISSUE TITLE
Коментарі для покручів стираються при генеруванні словника у візуальному форматі

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#263]
Багато лем, що є покручами, мають коментар з підказкою про правильний замінник. 
Наприклад: 
> агонізуючий /adj :&adjp:actv:imperf         #> що агонізує|охоплений агонією|в агонії|при смерті|напівживий

Але при генеруванні словника у візуальному форматі ця інформація зникає. [агонізуючий](https://r2u.org.ua/vesum/?w=%D0%B0%D0%B3%D0%BE%D0%BD%D1%96%D0%B7%D1%83%D1%8E%D1%87%D0%B8%D0%B9). Чи можна це виправити? 

[Місце в коді](https://github.com/brown-uk/dict_uk/blob/893e33e1aa52e9508b0ce2d1e00bfada2c3ef0f6/src/main/groovy/org/dict_uk/expand/TaggedWordlist.groovy#L54), де стирається цей коментар.

**Comment by arysin** [comment]
Насправді варіанти заміни не призначені для самого словника, ці коментарі генерують правила заміни для LanguageTool:
distr/morfologik-ukrainian/build.gradle - завдання "createReplacementDict" та інші.
Див. файли заміни тут https://github.com/languagetool-org/languagetool/tree/master/languagetool-language-modules/uk/src/main/resources/org/languagetool/rules/uk
Так само й деяка інша інформація, напр. керування відмінками тощо
