### ISSUE TITLE
Леми в geo-ukr-composite.lst генеруються без тегу geo.

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#264]
Леми в geo-ukr-composite.lst генеруються без тегу geo.

А такі слова, як "Брошнів-Осада", яке знаходиться не тільки в geo-ukr-composite.lst, а і в geo-other.lst генерує лему, яка водночас має тег geo і не має: 
https://r2u.org.ua/vesum/?w=Брошнів-Осада&all_forms=on

**Comment by arysin** [comment]
Дякую, виправлю.
