### ISSUE TITLE
Перенести groovy код на java

### ISSUE THREAD

**Issue by indegro** [brown-uk/dict_uk#265]
Добрий день.
Хотів би запитати, чи є плани перенести код, який наразі більшою частинюю написан на groovy на java. 
Якщо такі плани є, то я б залюбки допоміг. 

Я пробував виористати методи класу Expand у своєму проєкті, але не так вже й просто це зробити. 

Дякую и гарного дня.

**Comment by arysin** [comment]
Вітання, теоретично це можна зробити, але це буде значна витрата часу, якого немає. Цей код не мав на меті вбудовування в інші проєкти, і призначався суто для генерування словника форм.
Але якщо у вас є якась причина використати його у проєкті java можна спробувати дещо його допиляти, щоб викликати через GroovyScriptEngine.

**Comment by indegro** [comment]
Так, як варіант, можна викликати через GroovyScriptEngine, Думаю, що я можу досить швидко таке для себе зробити. 

ПС.
Які взагалі плани щодо коду? Чи планується перехід на джаву чи залишиться код на groovy?

**Comment by arysin** [comment]
Так, наразі планів переписувати немає, цей код писався декілька років і наразі якщо все працює, то, як на мене, не варто його чіпати :)
