### ISSUE TITLE
Kyiv must be Kyiv, nit kiev

### ISSUE THREAD

**Issue by boombyteOri** [brown-uk/dict_uk#266]
Чомусь кієв вважає правильним.

**Comment by arysin** [comment]
А про який засіб перевірки йде мова?

**Comment by boombyteOri** [comment]
Firefox. В мене лише цей встановлений. 
Чи це їхній вбудований, а цей тільки для української?
Потрібно прямо у лису писати?

**Comment by arysin** [comment]
Цей словник лише для Української. Для англійської, схоже, вбудований. Треба звітувати їм, але скоріш за все дивитися звідки вони беруть слова для англійського словника і правити вже там.
Для LanguageTool, я [додав](https://github.com/languagetool-org/languagetool/commit/5842bcc04e158957a15ad5910d6a54717ce2594a) назви українських за українським написанням/вимовою.
Вони, здається, занесли ці слова в aspell, але Firefox використовує hunspell, тож треба відстежувати.

**Comment by boombyteOri** [comment]
Зрозумів. Пардон, я не дуже розбираюся в цих термінах. Треба буде якось подивитись першоджерело їхнього партака.
