### ISSUE TITLE
Дублювання слів з тегом ua_2019

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#268]
Деякі слова, які мають тег _ua_2019_, дублюються. Наприклад, [бекетівський](https://r2u.org.ua/vesum/?w=%D0%B1%D0%B5%D0%BA%D0%B5%D1%82%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9), [вашингтонець](https://r2u.org.ua/vesum/?w=%D0%B2%D0%B0%D1%88%D0%B8%D0%BD%D0%B3%D1%82%D0%BE%D0%BD%D0%B5%D1%86%D1%8C) тощо.

Або ось з тегом long слово [борітеся](https://r2u.org.ua/vesum/?w=%D0%B1%D0%BE%D1%80%D1%96%D1%82%D0%B5%D1%81%D1%8F&all_forms=on) також дублюється.

**Comment by arysin** [comment]
Дякую, я ці випадки виправив.
