### ISSUE TITLE
Docker image doesn't build with error "/usr/bin/env: 'sh\r': No such file or directory"

### ISSUE THREAD

**Issue by ygolovnia** [brown-uk/dict_uk#269]
Step 2/6 : RUN apt update
 ---> Using cache
 ---> dd90250769d2
Step 3/6 : RUN apt install -y openjdk-8-jdk
 ---> Using cache
 ---> b3804db140fa
Step 4/6 : ADD . /src
 ---> Using cache
 ---> b3675290c851
Step 5/6 : WORKDIR /src
 ---> Using cache
 ---> 9fc0f7ea87a9
Step 6/6 : RUN ./gradlew expand
 ---> Running in 986617dcc528
/usr/bin/env: 'sh\r': No such file or directory
The command '/bin/sh -c ./gradlew expand' returned a non-zero code: 127

**Comment by arysin** [comment]
Is this on Windows?
