### ISSUE TITLE
Винести з &pron:def помилково внесене

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#27]

**Comment by arysin** [comment]
Перепрошую, не зрозумів, можна докладніше?

**Comment by msklvsk** [comment]
Пам’ятаєш з листів? До категорії <code>:def</code> помилково потрапили інші займенники.

**Comment by mariana-scorp** [comment]
@Olvija відпишеться, як внесемо зміни :)

**Comment by msklvsk** [comment]
@Olvija, здається ще лишилися. Чи взагалі існуть <code>:def</code> окрім _сам_, _самий_, _інший_, як написано у тому абзаці, котрий Василь наводив.
<pre>
інакше adv:&pron:def
інший adj:m:v_naz:&pron:def
онакий adj:m:v_naz:&pron:def:rare
перетакий adj:m:v_naz:&pron:def
по-всякому adv:&pron:def
по-іншому adv:&pron:def
сам adj:m:v_naz:&pron:def
самий adj:m:v_naz:&pron:def
сам-самісінький adj:m:v_naz:&pron:def
сякий adj:m:v_naz:&pron:def
сякий-такий adj:m:v_naz:&pron:def
такий-сякий adj:m:v_naz:&pron:def
який adj:m:v_naz:&pron:int:rel:def
</pre>

![def](https://cloud.githubusercontent.com/assets/473012/12507321/ba2d6a30-c0fd-11e5-9678-15302f6fbb47.jpg)

**Comment by msklvsk** [comment]
@mariana-scorp @vstarko
@arysin, reopen?

**Comment by mariana-scorp** [comment]
@msklvsk, отже, з **:def** залишаються слова:
1) інакше, інакший, інший, по-іншому, онакий (онакий==інший), сякий (http://sum.in.ua/s/sjakyj, займ. означ.), сякий-такий, такий-сякий, перетакий, який (в значенні "Який п'є, а який і трудиться.")
2) сам, самий, сам-самісінький

Вихованець, с. 206: «Означальні займенникові прикметники пов'язані з кількісно-означальною
семантикою. Цю групу займенникових прикметників репрезентують слова сам (самий) і інший.»

**Comment by mariana-scorp** [comment]
@msklvsk, чи бачиш ще щось підозріле?

**Comment by Olvija** [comment]
@msklvsk, @mariana-scorp, з **:def** ще "сякий-такий-перетакий"; 
а "сам-один" **:def** чи :**predic**?

**Comment by mariana-scorp** [comment]
@Olvija, "сякий-такий-перетакий" складеться правилами і буде :def :)
А "сам-один" - це цікаве питання. Воно в УЛІФі :predic і невідмінюване.

**Comment by msklvsk** [comment]
На хлопський розум, сюди не клеяться `adv`: _інакше_ і _по-іншому_ («Означальні займенникові **прикметники**…»). Яка історія в цих `adv`?

**Comment by mariana-scorp** [comment]
Вихованець,  с. 210: «5) атрибутивні  займенникові прислівники: інакше, по-іншому, по-всякому тощо»

**Comment by msklvsk** [comment]
Виходить, не лише той абзац регулює дефи? 5) — це пункт чого? Можеш дати pdf?
Чому ти тоді забрала `по-всякому`?

**Comment by mariana-scorp** [comment]
"По-всякому" обговорило кілька лінгвістів разом з "по-іншому". Погодили синхронізувати їх із прикметниками. Ти ж сам говорив про лінгвістичне чуття ;)
Книжку @Olvija хіба тобі кине. Мені зараз незручно її скинути.

**Comment by msklvsk** [comment]
Можеш тоді прописати тут чи в доках неформальну специфікацію дефу? Щоб коли люди питатимуть можна було їм показати. Типу …це отой абзац Вихованця + синоніми + іще абзац Вихованця, але не по-всякому.

**Comment by mariana-scorp** [comment]
Я додам окремий файл з розписаними видами займенників. Думаю, так всім легше стане)

**Comment by Olvija** [comment]
Про займенникові слова - наші рішення:
1. [займенникові іменники](https://docs.google.com/document/d/1CTvipaVMn3gOwAN30qvcIMQylRcqvOxiwOsbXu5KgC0/edit)
2. [займенникові прикметники](https://docs.google.com/document/d/1X1bhEOW3M5d3R6iisLSjiQ21U3Rw3SEDzsZR0-o1AiE/edit)
3. [займенникові прислівники](https://docs.google.com/document/d/1nJbxmVgINJhfuDhImGG0GlP9FPJ7lR0Rm2d1Kj36-1U/edit) 
4. [займенникові числівники](https://docs.google.com/document/d/1BeD_94uPFjR1dtCj61wb676DMkOmXAbQSnJKjTMpfWs/edit)

_Джерела:_
**Вихованець І. Р.** Теоретична морфологія української мови: Академ. граматика укр. мови / І. Вихованець, К. Городенська; За ред. І. Вихованця.— К.: Унів. вид-во “Пульсари”, 2004.— 400 с.
