### ISSUE TITLE
Іменник «передні»

### ISSUE THREAD

**Issue by danmysak** [brown-uk/dict_uk#273]
ВЕСУМ засвідчує сумнівний множинний іменник [«передні»](https://r2u.org.ua/vesum/?w=%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%BD%D1%96) із дивною моделлю відмінювання. Чи це не помилка?

**Comment by arysin** [comment]
Ми фіксуємо (частотні) випадки вжитку прикметників, як іменників, зокрема, як істот.
«передні» описано тут: http://sum.in.ua/s/perednij

>  у знач. ім. передні, ніх, мн. (передній, нього, чол.; передня, ньої, жін.). Ті, що стоять, пересуваються, рухаються попереду інших. Компанія Піхоти з маршу йде.., мов клин, Іде в той стиск... «Набік! Набік!» Та де тобі! Передніх тиснуть задні (Іван Франко, XIII, 1954, 311); Запорожці палили, не зводячи духу. Задні заряджали рушниці переднім

**Comment by danmysak** [comment]
Зрозуміло. Але форми все ж помилкові: мало бути «передніх» замість «передних», «переднім» замість «передним» і «передніми» замість «передними».

**Comment by arysin** [comment]
Так, ваша правда, я виправлю, дякую!!
