### ISSUE TITLE
Немає :ranim для числівників, прикметникових займенників, множини

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#28]
<pre>
  …
  один   numr:m:v_zna
  одного numr:m:v_zna
  …
</pre>

<pre>
  …
  цей   adj:m:v_zna:&pron:dem
  цього adj:m:v_zna:&pron:dem
  …
</pre>

<pre>
  …
  жваві  adj:compb:p:v_zna
  жвавих adj:compb:p:v_zna
  …
</pre>

**Comment by mariana-scorp** [comment]
Гляну, дякую.

**Comment by arysin** [comment]
Цей, здається, можна закрити?

**Comment by msklvsk** [comment]
ще лишаються числівники, зокрема перший приклад

**Comment by arysin** [comment]
А можна приклад, де ще немає, бо ось є для один:
один один adj:m:v_zna:rinanim:&pron:dem:ind
одного один adj:m:v_zna:ranim:&pron:dem:ind

**Comment by msklvsk** [comment]
<pre>один   numr:m:v_zna
одного numr:m:v_zna
</pre>

**Comment by arysin** [comment]
А чи може взагалі бути одного numr:m:v_zna ?

**Comment by mariana-scorp** [comment]
Може :) Кажучи "одного хлопця", ти можеш мати на увазі "одного", а не "двох" (числівник) або "одного" в значення "якогось".

Додала :ranim поки для множини прикметникових займенників і для "один".

**Comment by arysin** [comment]
Чи це питання вже можна закрити?

**Comment by msklvsk** [comment]
ще лишається множина (одинадцять/одинадцятьох), правильно?

**Comment by vstarko** [comment]
Ось цитата з "Теоретичної морфології української мови", яка показує, що тут є хитання. Якщо визнати, що можливі паралельні правильні конструкції _Я бачу дві гарні жінки/двох гарних жінок._, то під сумнівом опиняється тег :ranim і для прикметників у з.в.мн.
![numr_and_ranim](https://cloud.githubusercontent.com/assets/8600477/14467143/98502f4a-00e2-11e6-88db-fd9f7120aa31.jpg)

**Comment by arysin** [comment]
Закриваємо, див. цитату з Теорграматики
