### ISSUE TITLE
Ужок - помилки в парадигмі

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#285]
Там не має бути випадання. Див. [тут](https://r2u.org.ua/vesum/?w=%D0%A3%D0%B6%D0%BE%D0%BA&all_forms=on).

**Comment by arysin** [comment]
Дякую, виправлю. Але схоже в текстах майже - в ГРАКу 15 Ужка і 13 Ужока.

**Comment by vstarko** [comment]
тоді варто мати два варіанти

**Comment by arysin** [comment]
Цікаво, що в УЛІФі У́жок, а у Вікіпедії Ужо́к
