### ISSUE TITLE
Родовий відмінок на -а/-у

### ISSUE THREAD

**Issue by shvedova** [brown-uk/dict_uk#291]
В корпусі дуже багато ненормативних форм, вони не тегуються.

**Comment by arysin** [comment]
На жаль ці форми дуже часто перетинаються з рос. словами, тому тут дуже важко зробити щось швидко

**Comment by vstarko** [comment]
Якщо є ненормативне -у (замість -а), то не має перетинатися з рос. — можна додати в парадигму з тегом :subst. Зрештою є живомовна тенденція до розширення вживання -у в род.в.
Якщо ж є ненормативне -а (замість -у), то справді може перетинатися з рос. —  тоді можна додати в парадигму з тегом :bad. Навіть якщо це рос. слово, то воно дістане тег :bad. А на ідентифікацію мови (укр. чи рос.) вплине дуже несуттєво.
Якщо це ОК, то можна створити список таких слів.

**Comment by arysin** [comment]
Duplicate for #113
