### ISSUE TITLE
Тирамісу, а не "Тірамісу"

### ISSUE THREAD

**Issue by Alex-7** [brown-uk/dict_uk#293]
Тірамісу чи тирамісу - експрес-урок https://youtu.be/X3y4nVSO93o

Добрый день! 
Исправьте, пожалуйста, в спеллчекинге. Правильно пишется на украинском: Тирамісу.
Посмотрите, пожалуйста, видео (ссылка выше), где это объясняется.
С уважением,
Алексей

**Comment by arysin** [comment]
Дякую, виправлено.

**Comment by Alex-7** [comment]
Спасибі!
