### ISSUE TITLE
Зарелізніть нову версію, будь ласка

### ISSUE THREAD

**Issue by kuraga** [brown-uk/dict_uk#302]
Останній [тег](https://github.com/brown-uk/dict_uk/tags)/[версія](https://extensions.libreoffice.org/en/extensions/show/ukrainian-spelling-dictionary-and-thesaurus) - 5.6.0, але зараз [бачу](https://github.com/brown-uk/dict_uk/blob/7961e73362fa6f9edaa81f09510dffc689658132/VERSION#L1) 5.7.7.

Зарелізніть нову версію, будь ласка.

Дякую.

**Comment by arysin** [comment]
Вийшла версія 5.8.0

**Comment by kuraga** [comment]
:+1:

**Comment by kuraga** [comment]
:+1: 
@arysin, [тут](https://extensions.libreoffice.org/en/extensions/show/ukrainian-spelling-dictionary-and-thesaurus)?

**Comment by arysin** [comment]
Я закинув нову версію розширення, воно інколи день-другий займає чомусь.

**Comment by arysin** [comment]
Вже опублікували oxt 5.8.0
