### ISSUE TITLE
Стоп-слова "і" та "та"

### ISSUE THREAD

**Issue by sergiig** [brown-uk/dict_uk#305]
Вітання!

Прошу розглянути можливість розширити перелік стоп-слів для PostgreSQL словами _"і"_ та _"та"_.

Зараз ці слова сприймаються як звичайні. Наприклад:

```PLpgSQL
select plainto_tsquery('ukrainian', 'Міністерство освіти і науки');
```

поверне 

```
'міністерство' & ( 'освіта' | 'освітити' | 'освіта' ) & 'і' & 'наука'
```

Тобто для тексту _"міністерство освіти і науки"_ повнотекстовий пошук за запитом _"міністерство освіти **та** науки"_ не знайде нічого. Думаю є багато інших випадків де така поведінка буде небажаною.

**Comment by arysin** [comment]
Дякую, зроблено

**Comment by sergiig** [comment]
Дуже дякую, @arysin !
