### ISSUE TITLE
Володимир-Волинський

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#309]
і відповідний прикметник має дістати в словнику alt, бо в кінці 2021 офіційно [перейменували](https://uk.wikipedia.org/wiki/%D0%92%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_(%D0%BC%D1%96%D1%81%D1%82%D0%BE)#%D0%9D%D0%B0%D0%B7%D0%B2%D0%B0) на Володимир.

**Comment by arysin** [comment]
Ми наразі не додаємо alt до перейменованих назв, але даємо їм заміну через #>> і тоді спрацьовує відповідне правило
