### ISSUE TITLE
Неправильні форми р.в. мн.: солдат, турок...

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#310]
у текстах часто зустрічається 10 солдат, 5 турок тощо.
Якщо їх не подавати то правописник (добре) редагує на 10 солдат, але тоді при тегуванні цієї форми немає. Якщо додати солдат :p:...bad тоді додається форма, але створюється омонімія для правильних випадків.

**Comment by vstarko** [comment]
Пропоную цю неправильну форму в словник не додавати, а спробувати виловлювати неправильні вживання правилом у Правописнику. Автоматично тегуватиметься неправильно (як н.в. одн.) — ну але тут немає ради. Принаймні лема буде правильна.
