### ISSUE TITLE
Чоловіче ім'я - Сила

### ISSUE THREAD

**Issue by sergiiman** [brown-uk/dict_uk#311]
Прошу розглянути можливість внесення в словник чоловічого імені "Сила" та його словоформ (https://uk.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BB%D0%B0_(%D1%96%D0%BC%27%D1%8F)).

Виникла ситуація, коли в словнику не знайшов по батькові, жіночого роду "Силівна", як похідного від імені Сила.

**Comment by arysin** [comment]
Вітання, дякую за звіт, але ВЕСУМ орієнтується на практичне застосування, здебільшого на сучасні тексти.
В текстах Силівна майже не зустрічається (в ГРАКу немає і гугл дає фактично один випадок), Сила теж страшенно рідке і має ще й недолік в тому, що створює омонімію з дуже поширеним словом «сила» (у ГРАКу практично всі випадки «Сила» - це загальне слово).
Тобто для академічних словників, з огляду на повноту, ці слова мають сенс, але для практичного вжитку/NLP особливо сучасних текстів не думаю, що варто їх додавати

**Comment by sergiiman** [comment]
Я цілком з Вами згодний, що це випадок страшенно рідкісний. Але ми його зустріли саме в практичній площині - використовуючи Ваш словник наше програмне рішення не може отримати необхідних знань по слову "Силівна" (по батькові, жіночого роду).
Прошу Вас, по можливості, зазначити правило словотворення для цього випадку, щоб ми змогли добавити його в наш форк проєкту. На жаль у нас недостатньо знань, щоб зробити це самостійно.

**Comment by arysin** [comment]
Найпростіше додати такий рядок в names-anim.lst:
Сила /n10.<m.patr

**Comment by sergiiman** [comment]
Я дуже вам вдячний. Питання закрите повністю.
