### ISSUE TITLE
Dictionary origins

### ISSUE THREAD

**Issue by bzaar** [brown-uk/dict_uk#315]
First of all, thanks for your amazing work. This repository's history dates back to October 2015. What are the origins of this dictionary? At the time ```base.lst``` was first committed, it already [had](https://github.com/brown-uk/dict_uk/commit/f35747a4ade8eca747de10fe337fd4643348d7cc#diff-8d94da3f8498957d789b1bcdbb40e66fb5cd70aee2ce01fcf89e6e87be1705a6) 141,368 lines. This makes me wonder where all those lines came from. Just curious!

**Comment by arysin** [comment]
Hi, the source of this project is https://sourceforge.net/projects/ispell-uk/
