### ISSUE TITLE
Слова з апострофом: зміна символу після виправлення

### ISSUE THREAD

**Issue by trumpeti100** [brown-uk/dict_uk#317]
У текстових редакторах, які підтримують роботу з українським словником, під час виправлення слова з апострофом водночас змінюється і символ апострофа: замість апострофа (традиційно схожий на кому) з'являється, "прямий кілок".
Див. приклади (ситуація у LibreOffice Writer) .

Слово з апострофом:
![image](https://user-images.githubusercontent.com/29570967/219113749-e9a6c029-88aa-4f85-8f4a-6c2411edc5c9.png)

Слово після виправлення (апостроф змінився):
![image](https://user-images.githubusercontent.com/29570967/219114520-b7d81555-d2bb-4b5c-a9ba-f8343e9034bd.png)

**Comment by arysin** [comment]
Дякую за звіт, на жаль це не дуже просто. Наразі ми маємо список слів з апострофами один раз (з прямим) і маємо директиву, що інші (два) треба трактувати так само. Тож коли йде заміна береться слово з бази з прямим.
Єдине розв'язання цієї проблеми - дублювати слова з апострофом в списку для кожного варіанту апострофа (тобто наразі слова з апострофом треба повторювати три рази), також інша проблема з цим підходом, що всі виправлення де пропонуються слова з апострофом будуть пропонуватися тричі, а враховуючи, що кількість пропозицій часто обмежена, то потрібні варіанти можуть в список не потрапити через це

**Comment by trumpeti100** [comment]
Дякую за відповідь! Ситуацію зрозумів.

Утім, якщо мати справу з масивом текстової інформації, подібні слова з прямим апострофом, особливо у шрифтах, на зразок Times New Roman чи Liberation Serif, все ж виглядають, як помилки. Відтак кожне таке слово приходиться змінювати вручну. А коли текст об'ємний, то це складає неабияку проблему.

Для інформації.
Перевірив - Google Docs також при зміні слів з апострофом працює так само, як я описував вище.
Працюю в Linux, тому навмисно пробував ряд текстових процесорів, які працюють у цій ОС і мають широкий функціонал роботи з текстами - OnlyOffice, WPS Office, FreeOffice, а також LibreOffice і OpenOffice.

Так ось, лише [FreeOffice](https://www.freeoffice.com/) і, відповідно, його платна версія [SoftMaker Office](https://www.softmaker.com/), працюють коректно з пропонованим [українським словником](https://www.freeoffice.com/ru/download/dictionaries) - помилкові слова з апострофом виправляються, але при цьому символ апострофа завжди залишається незмінним  і правильним, тобто =
![image](https://user-images.githubusercontent.com/29570967/219417968-0e445734-d242-4a70-8af8-ece3eb534efe.png)

**Comment by arysin** [comment]
Всі ці ПЗ використовують hunspell і словник ВЕСУМ для перевірки
української. Тож вони всі має реагувати відносно однаково. Можливо
FreeOffice має якусь особливу логіку (хоча це було б дивно), але їх
український словник - це дуже стара версія ВЕСУМу (але з тими самими
атрибутами для апострофів).
Якщо прямий апостроф небажаний, може його можна було б потім поміняти
глобальною заміною?

**Comment by trumpeti100** [comment]
Дякую за пояснення!
Щодо заміни символу глобально, то я це якраз планую зробити.
Принагідно дякую щиро за підтримку українського словника. Ви реалізуєте - важливу справу!
Бажаю наснаги й успіхів!
Слава Україні!

**Comment by arysin** [comment]
Дякую, Героям Слава!
