### ISSUE TITLE
Libreoffice не оновлює словник

### ISSUE THREAD

**Issue by burunduk** [brown-uk/dict_uk#327]
В дистрибутив LibreOffice 7.6 входить словник версії 5.8
На порталі розширень опубліковано оновлений словник версії 6.1.0
При запиті оновлення розширення вручну, оновлення словника не знаходить.

**Comment by arysin** [comment]
Вітання, не зміг відтворити проблему: поставив розширення 5.8, натиснув шукати оновлення, знайшло 6.1.0 і встановило. Щоправда, у мене LibreOffice 7.5.5

**Comment by burunduk** [comment]
Проблема виникає, якщо встановити реліз (на даний момент 7.6)

**Comment by archdron** [comment]
Маю LibreOffice 7.6, встановлений із Flatpak на Fedora 38.
LanguageTool там вбудований не доповненням а функціональністю API, тож він дзвонить на віддалені сервери й уже там виконується вся перевірка.
Щоб оновити треба завантажити його як доповнення з [каталогу LibreOffice Extensions](https://extensions.libreoffice.org/en/extensions/show/languagetool)

**Comment by arysin** [comment]
Щойно поставив Libreoffice 7.6 з flatpak на Fedora 38, встановив словник 5.8 вручну, натиснув шукати оновлення, знайшло і встановило 6.1.0:

Version: 7.6.0.3 (X86_64) / LibreOffice Community
Build ID: 69edd8b8ebc41d00b4de3915dc82f8f0fc3b6265
CPU threads: 20; OS: Linux 6.4; UI render: default; VCL: gtk3
Locale: en-US (en_US.UTF-8); UI: en-US
Flatpak
Calc: threaded

**Comment by burunduk** [comment]
Тоді проблема чисто win збірок. Перевірив на версії 7.5, та оновив до 7.6. Видаляю розширення, лишається словник версії 5.8 (йде в комплекті релізу і не видаляється). Натискаю пошук оновлення - немає оновлень.

**Comment by arysin** [comment]
Я підозрюю проблема не у віндовій збірці, а в локалізаційному пакеті. Якщо ваш LO йде з українським словником, то це мабуть українська локалізація. І вона містить розширення словника в собі.
Для того, щоб словник вмів автоматично оновлюватися всередині розширення у файлі descriptions.xml має бути розділ <update-information>, якщо вони його вилучили (або змінили url) то він шукати оновлення не буде.

**Comment by arysin** [comment]
Так і є: заглянув у вміст локалізаційного пакунку для Лінукс:
Там є libreoffice7.6-dict-uk-7.6.0.3-3.x86_64.rpm і в ньому descriptions.xml не має розділу update-information
