### ISSUE TITLE
людини noun:anim:p:v_zna:rare # з в/у

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#329]
В парадигмі леми "людина" є такі два записи  
людини noun:anim:p:v_zna
людини noun:anim:p:v_zna:rare # з в/у
Другий з них — зайвий.
Та сама проблема:
дівчини noun:anim:p:v_zna:rare # з в/у

**Comment by vstarko** [comment]
Так

**Comment by arysin** [comment]
дякую, виправив
