### ISSUE TITLE
форми молодеж- з :rare 

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#331]
Це насправді застарілі форми, тож треба їх позначити як :arch.
Те саме стосується:
форми "жаден" від леми "жадний" - теж :arch 
форми вістен adj:m:v_naz:short:rare - теж :arch 
леми многий - саму лему й усі словоформи в її парадигмі слід позначити :arch ("многії/многая літа" — це архаїчне вкраплення в сучасному мовленні)

**Comment by arysin** [comment]
дякую, виправив
