### ISSUE TITLE
Змінити посилання в описі з https://r2u.org.ua/vesum/ на https://vesum.nlp.net.ua/

### ISSUE THREAD

**Issue by alinkedd** [brown-uk/dict_uk#336]
Було б доцільно замінити посилання  в README та [на сайті](https://vesum.nlp.net.ua/) з https://r2u.org.ua/vesum/ на основний таргет після редиректу https://vesum.nlp.net.ua/:
> Просимо посилатися на вебверсію ВЕСУМу так:
> Рисін А., Старко В. Великий електронний словник української мови (ВЕСУМ). Вебверсія 6.1.0. 2005-2023. URL: https://vesum.nlp.net.ua/
> Rysin, A., Starko, V. Large Electronic Dictionary of Ukrainian (VESUM). Version 6.1.0. 2005-2023. Available at: https://vesum.nlp.net.ua/

**Comment by arysin** [comment]
Дякую, виправлено
