### ISSUE TITLE
гуля

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#341]
Правильно: ґуля. В сенсі "голуб" слово "гуля" трапляється дуже рідко.
У ВЕСУМі гуля :bad.
Але Правописник або не виловлює взагалі ("кому — пироги й млинці, а кому — гулі й синці"), або не пропонує правильного варіанта з ґ (див. знімок).
![image](https://github.com/brown-uk/dict_uk/assets/8600477/455295a9-3ab0-4d03-99be-7d1eb45493be)

**Comment by arysin** [comment]
«гулі» - має омонімію гулі noninfl, тому воно не підкреслюється
Щодо пропозицій виправлення в наступній версії буде
