### ISSUE TITLE
Між тим - Тим часом; Проте

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#342]
На початку речення "Між тим," зазвичай є калькою з рос. Между тем — окрім відносно нечастих випадків на кшталт "Між тим, що вони говорять, і тим, що роблять, зяє величезна прірва."
Тож можна в Правописник додати таке правило: якщо цей зворот стоїть на початку речення і після нього не йде іменникова лема "що" .

**Comment by arysin** [comment]
Додано
