### ISSUE TITLE
користуватися (чиєюсь) довірою -> мати (чиюсь/чиєсь) довіру/довір'я 

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#343]
Це калька з рос. пользоваться доверием.
Формулювання правила заміни ускладнює той факт, що в реченні ключові слова "користуватися" й "довіра" можуть бути розмежовані одним, двома чи більше словами. Можливий також порядок "довірою" .... "користуватися".
Значно рідше (приблизно в 5-6 разів) трапляється хибна конструкція з "користуватися" й "довір'я".

**Comment by arysin** [comment]
Додано
