### ISSUE TITLE
Тайпей

### ISSUE THREAD

**Issue by bicolino34** [brown-uk/dict_uk#378]
Альтернативна транслітерація назви столиці Тайваню „Тайбею“

[ГРАК](https://parasol.vmguest.uni-jena.de/grac_crystal/#concordance?corpname=grac17&tab=advanced&queryselector=cql&keyword=%D0%BF%D0%B8%D0%B7%D0%B4%D0%B8%D1%82%D0%B8&attrs=word%2Clemma%2Ctag%2Csemtag&viewmode=sen&attr_allpos=kw&refs_up=1&shorten_refs=0&glue=0&itemsPerPage=500&structs=s&refs=%3Ddoc.date%2C%3Ddoc.title%2C%3Ddoc.author&default_attr=lemma&cql=%5Bword%3D%22%D0%A2%D0%B0%D0%B9%D0%BF%D0%B5.*%22%5D&showresults=1&f_tab=advanced&c_itemsPerPage=500&c_customrange=1&operations=%5B%7B%22name%22%3A%22cql%22%2C%22arg%22%3A%22%5Bword%3D%5C%22%D0%A2%D0%B0%D0%B9%D0%BF%D0%B5.*%5C%22%5D%22%2C%22active%22%3Atrue%2C%22query%22%3A%7B%22queryselector%22%3A%22cqlrow%22%2C%22cql%22%3A%22%5Bword%3D%5C%22%D0%A2%D0%B0%D0%B9%D0%BF%D0%B5.*%5C%22%5D%22%2C%22default_attr%22%3A%22lemma%22%7D%2C%22id%22%3A5928%7D%5D)

Також відповідний прикметник: тайпейський

**Comment by arysin** [comment]
Дякую, додамо

**Comment by arysin** [comment]
Додано
