### ISSUE TITLE
бітний і бітовий

### ISSUE THREAD

**Issue by alinkedd** [brown-uk/dict_uk#381]
`бітний` має позначку bad, хоча і `бітовий`, і `бітний` можуть використовуватися, бо мають різний відтінок і контекст:
- `бітовий` стосується характеристики `біта`, 
- `бітний` стосується кількості `біт`

Джерело:
https://ukrainian.stackexchange.com/questions/1111/%D0%AF%D0%BA-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE-%D0%B1%D1%96%D1%82%D0%BD%D0%B8%D0%B9-%D1%87%D0%B8-%D0%B1%D1%96%D1%82%D0%BE%D0%B2%D0%B8%D0%B9-%D0%B1%D1%96%D1%82%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D1%87%D0%B8-%D0%B1%D1%96%D1%82%D0%BE%D0%B2%D1%96%D1%81%D1%82%D1%8C

Чому `бітний` було позначено неправильним? Чи можливо це змінити?

**Comment by vstarko** [comment]
Дякую за заувагу. Справді, бітний годиться. Треба зняти :bad. 
Плюс варто додати в словник: бітовість, бітність — теж як прийнятні слова.

**Comment by arysin** [comment]
Дякую, знімемо `:bad` для бітний в наступному випуску.
