### ISSUE TITLE
клацати/клацнути зі знахідним відмінком

### ISSUE THREAD

**Issue by alinkedd** [brown-uk/dict_uk#382]
Дієслова `клацати`/`клацнути` вимагають лише орудного відмінка.
Чи можна дозволити використовувати їх зі знахідним відмінком?

Проблема полягає у тому, щоб:
- перестати вживати кальковані `клікати`/`клікнути` (які зазвичай у розмовній мові йдуть зі знахідним відмінком: клікнути [на] кнопку)
- зберегти відмінність між значеннями, але залишити однаковість вживання для слів `клацати`/`клацнути` та `тиснути`/`натиснути`/`натискати` під час перекладу виразів `click (on) the button/key` і `press the button/key`

**Comment by arysin** [comment]
дякую, додамо знахідний теж

**Comment by alinkedd** [comment]
Зроблено в https://github.com/brown-uk/dict_uk/commit/16800c88ac46c27747efdb9687b7fde2e6916b82

**Comment by arysin** [comment]
Закинув у LT, наразі це на https://check.nlp.net.ua, але за день-другий має бути в офіційній версії.
