### ISSUE TITLE
Некоректні покручі

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#384]
Наступні слова позначені покручами, хоча, ймовірно, ними не є, оскільки вони наявні в академічних словниках (в СУМ-20 або в https://lcorp.ulif.org.ua/dictua/)

1. авіаобробка
2. автогідропідйомний   
3. автогідропідйомник   
4. автогоночний                 
5. автолавка                         
6. аглютинуючий               
7. агонізуючий                    
8. агонуючий                       
9. ад                                
10. аерозйомка                     
11. аерофотозйомка           
12. азбостальний                 
13. азотокислий                   
14. акаючий                            
15. Акерман                           
16. активнодіючий              
17. альпаговий                     
18. амбіціозний                    
19. амбіціозність                  
20. амбіціозніший               
21. амбіціозно                       
22. аміаковий                        
23. аналгезуючий                
24. анестезуючий
25. ...

**Comment by arysin** [comment]
СУМ є тлумачним словником, якщо слова зустрічаються в джерелах такий словник має подавати тлумачення.
Граматична/стилістична правильність - інший критерій, для цього існують орфографічні словники, але на жаль й вони не викривають всіх аспектів. 
Більшість мовознавців погоджуються, що активні дієприкметники теперішнього часу невластиві українській мові, тож їх варто уникати. 
Також правильна назва міста - Аккерман (тож з однією - помилка).
азбостальний  - покруч, бо немає прикм. «стальний», тож правильно «азбосталевий»
амбіціозний - калька з рос. (див. https://r2u.org.ua/s?w=%D0%B0%D0%BC%D0%B1%D0%B8%D1%86%D0%B8%D0%BE%D0%B7%D0%BD%D1%8B%D0%B9&scope=all&dicts=all&highlight=on)
і т.д.
ВЕСУМ найбільший український словник з лінгвістичними атрибутами і він вичитувався й вивірявся багато років тож вивіряти його на інших словниках можна лише вибірково. Не те, щоб там не було помилок, але вони будуть несистемні.
