### ISSUE TITLE
Двовидові дієслова мають некоректний майбутній доконаний час 

### ISSUE THREAD

**Issue by Palindromer** [brown-uk/dict_uk#385]
Усі доконані леми двовидових дієслів мають некоректні слова для майбутнього часу. Замість майбутнього часу там визначені слова для теперішнього часу.

Наприклад: 

1. [автоматизувати](https://vesum.nlp.net.ua/?w=автоматизувати&all_forms=on&format=on)
2. [адресувати](https://vesum.nlp.net.ua/?w=адресувати&all_forms=on&format=on)
3. [глобалізувати](https://vesum.nlp.net.ua/?w=глобалізувати&all_forms=on&format=on)

**Comment by arysin** [comment]
не зовсім зрозумів проблему - «автоматизую» є тепер. ч. для недокон. «автоматизувати» (я автоматизую це зараз), і майб. ч. для докон. «автоматизувати» (я автоматизую це завтра).

**Comment by Palindromer** [comment]
Так, ваша правда. Вибачте, не відразу зрозумів, як дієслово у теперішньому часі може бути таким же і для майбутнього. 😅
