### ISSUE TITLE
байдарочник та інші слова на -очник

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#389]
ці леми треба перемістити у twisters із такими замінами:
байдарочник - байдарник, байдаркар
байдарочниця - байдарниця, байдаркарка
бородавочник - бородавник
будочник - будник
булочник - пекар
двійочник - двієчник
лоточник - яточник
пробочник - коркотяг

**Comment by arysin** [comment]
а також:
булочниця і лоточниця?

**Comment by vstarko** [comment]
Так. Якщо є відповідні фемінітиви, то їх теж треба у twisters і правити.

**Comment by arysin** [comment]
зроблено
