### ISSUE TITLE
число для числівників _два_, _півтора_, _тис._

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#39]
Немає позначки множини (чи двоїни) для _два_ і подібних (типу бо є рід). І такі слова можуть  додаватися ще, без позначки числа ніяк.

**Comment by mariana-scorp** [comment]
Зараз у словнику слова мають або рід, або позначення множини. І того, і того одночасно нема, але в планах є додати позначку роду для множини іменника. Думаю, в межах цієї задачі можна додати позначку множини для числівників. @arysin, як гадаєш?

**Comment by msklvsk** [comment]
> в планах є додати позначку роду для множини іменника 

Існують випадки коли рід множини іменника не можна взяти з леми?

**Comment by mariana-scorp** [comment]
Ми думали додати інформацію про рід як додаткову, оскільки питання позначки роду в формах множини вже порушувалось мінімум двічі:
- в контексті правил для LT
- в контексті інтеграції словника в pymorphy2

Поки цим не займались, але будуть випадки на кшталт `судді noun:anim:p:v_naz`, де може бути і мікс чоловіків з жінками, тож не всюди рід буде потрібен і буде однозначним)

**Comment by arysin** [comment]
«категорію числа у числівниках майже повністю нейтралізовано» (Теорграматика, с. 168)
