### ISSUE TITLE
назви жінок на -ша перемістити у twisters із заміною

### ISSUE THREAD

**Issue by vstarko** [brown-uk/dict_uk#392]
Наразі більшість з них уже там, але треба пересунути ще такі (крім тих, що мають значення "дружина такого-то", як-от генеральша, гетьманша):

байкерша #> байкерка
банкірша  #> банкірка
барменша #> барменка
бізнесменша  #> бізнесменка
вахтерша #> вахтерка
кастелянша #> каштелянка
мільйонерша #> мільйонерка

**Comment by arysin** [comment]
зроблено
