### ISSUE TITLE
Декілька відсутніх слів

### ISSUE THREAD

**Issue by alinkedd** [brown-uk/dict_uk#415]
із хвороб:
- [обсесивно-компульсивний](https://uk.wikipedia.org/wiki/%D0%9E%D0%B1%D1%81%D0%B5%D1%81%D0%B8%D0%B2%D0%BD%D0%BE-%D0%BA%D0%BE%D0%BC%D0%BF%D1%83%D0%BB%D1%8C%D1%81%D0%B8%D0%B2%D0%BD%D0%B8%D0%B9_%D1%80%D0%BE%D0%B7%D0%BB%D0%B0%D0%B4)
- [Аспергер](https://uk.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BD%D0%B4%D1%80%D0%BE%D0%BC_%D0%90%D1%81%D0%BF%D0%B5%D1%80%D0%B3%D0%B5%D1%80%D0%B0)
- [дискалькулія](https://uk.wikipedia.org/wiki/%D0%94%D0%B8%D1%81%D0%BA%D0%B0%D0%BB%D1%8C%D0%BA%D1%83%D0%BB%D1%96%D1%8F)

із програмування:
- [вебкомпонент](https://uk.wikipedia.org/wiki/%D0%92%D0%B5%D0%B1_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B8)
- вебтехнологія
- [вебфреймворк](https://uk.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D0%BA%D0%B0%D1%81_%D0%B2%D0%B5%D0%B1%D0%B7%D0%B0%D1%81%D1%82%D0%BE%D1%81%D1%83%D0%BD%D0%BA%D1%96%D0%B2)
- метафреймворк
- [метапрограмування](https://uk.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%B0%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)
- [монорепозиторій](https://en.wikipedia.org/wiki/Monorepo) (en)
- [безсерверний](https://uk.wikipedia.org/wiki/%D0%91%D0%B5%D0%B7%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BD%D1%96_%D0%BE%D0%B1%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F)

**Comment by arysin** [comment]
Дякую, додано
