### ISSUE TITLE
“піти в солдати”,  “їх було з десять” — rv_naz?

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#42]
Андрій сказав, що про це щось було в Синявського, але я швидко не знайшов.
Проте є в СУМі: “…8. із знах. (у давній формі, яка збігається з сучасним називним множини)” (http://sum.in.ua/s/v)
Нехай знахідний у давній формі, але солдати в словнику зараз або <code>солдати noun:anim:p:<b>v_naz</b></code> або <code>солдати noun:anim:p:<b>v_kly</b></code>, тож зробити щось треба: або додати давній знахідний, або додати <code>:rv_naz</code>, або? Що скажете?

**Comment by o-pikozh** [comment]
А є якість недоліки чи побічні ефекти того, щоб вважати це називним?

**Comment by arysin** [comment]
Недолік називного, бо іменник стоїть після прийменника, який вимагає знахідний.

http://r2u.org.ua/guides/synyavsky/slovozmina_imennyk

> ...Навпаки, знахідний відмінок від назов людей не завсіди дорівнюється тільки родовому, а ще й назовному. Це навіть обов’язково в тих випадках, коли таке додаткове слово після прийменника разом із цим останнім сталося прислівниковим виразом чи хоч наблизилося до прислівника, напр.: "вийти в люди", "піти в учителі", "записатися в міщани", "пошитися в дурні" тощо. Навіть і в інших випадках знахідний відмінок множини від назов людей може дорівнюватися назовному, а не родовому, як от "хустки на молодиці" тощо, а в Шевченка, напр., такі вирази, як "серце люди полюбило", досить звичайні і становлять одну з стилістичних особливостей його.

**Comment by o-pikozh** [comment]
Ні, це я розумію, що насправді там особлива форма знахідного (а називний може бути лише в підметі) -- але чи будуть побічні ефекти того, що програма вважатиме його називним? Якщо це ніяк ніде потім негативно не випливе (те, що програма всередині вважатиме його називним), то, як на мене, немає сенсу додавати давній знахідний.

**Comment by arysin** [comment]
З погляду анотування корпусу не знаю, а для перевірки граматики наразі мені
доводиться для таких випадків писати код, щоб вони ігнорувалися (бо інакше
аналізатор знаходить називний після прийменника і свариться).

12 січня 2016 р. о 19:41 o-pikozh <notifications@github.com> написав:

**Comment by mariana-scorp** [comment]
Граматично це знахідний відмінок. Називний не може після прийменника йти. Якщо в корпусі виникне потреба проанотувати щось подібне, то анотуватимемо однозначно як знахідний.

Якщо і додавати `солдати noun:anim:p:v_zna`, то тільки з позначкою `:rare`. Є ще частотніше "вийти в люди", яке теж варто додати.

**Comment by arysin** [comment]
Гаразд, тоді я думаю це тре робити в модулі зняття омонімії. Я подумаю чи
варто цей тег заводити в словник.

**Comment by msklvsk** [comment]
Вийти, піти, податися, пробитися можна в кого завгодно. Системно буде додати <code>:v_zna</code> всім або нікому.

@arysin який тег?

**Comment by mariana-scorp** [comment]
У фразі “їх було з десять” слово "з", таке враження, відіграє роль прислівника. Треба дослідити. Може, Василь тут щось додати зможе.

**Comment by arysin** [comment]
@msklvsk v_zna:rare
Тобто можна або додати цей тег в словник і потім знімати омонімію в LT, або
не додавати в словник а в LT міняти такі випадки v_naz -> v_zna

**Comment by msklvsk** [comment]
як на мене, то не додавати зовсім і перенести логіку в LT краще ніж додавати для одиничних разів

**Comment by mariana-scorp** [comment]
Згода.

**Comment by msklvsk** [comment]
для історії: жодних змін у словник в решті решт внесено не було

**Comment by arysin** [comment]
Пардон, відкриваю назад, хай висить, поки логіку в LT не додамо.

**Comment by mariana-scorp** [comment]
Cast @vstarko.

**Comment by vstarko** [comment]
конструкції типу "піти в солдати" - на рівні морфаналізу "солдати" наз.в., на рівні синтаксичної структури - знах.в. Ліпше автоматично тегувати як наз.в., а потім, за потреби, використовувати логіку (або руки) й міняти на знах.в.
“їх було з десять” - знах. в. - [http://sum.in.ua/s/z](url) значення 1

**Comment by mariana-scorp** [comment]
Як їх тоді анотувати? Під час синтаксичного аналізу ти відмінок не мінятимеш.

**Comment by vstarko** [comment]
Поки не знаю. Ми домовилися, що морфаналіз проводимо послівно, на рівень фраз не виходимо. За таким принципом "солдати" - це лише наз.в. Якби можна було додати якусь постморфаналізну логіку (додатковий рівень після морфаналізу), на якому передбачити заміну в+noun:v_naz замінити на в+noun:v_zna. Щось таке. Можливо, таких правил назбирається і на рівні постморфаналізу ми зможемо прибрати трохи омонімії автоматично.

**Comment by arysin** [comment]
Ми додали ці форми з.в. як noun:anim:p:v_zna:rare
