### ISSUE TITLE
Додати присвійні прикметники

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#55]
Від усіх імен (тег fname), крім незмінюваних (типу Джекі), слід утворити й ввести в словник присвійні форми.

**Comment by msklvsk** [comment]
NB: нерідко трапляються присвійні і від прізвищ

**Comment by arysin** [comment]
Я додав багато присвійних і деякі імена, до яких були присвійні, але самих імен не було.
Взагалі присвійні не до всіх пасують, зокрема до неслов'янських імен.
І до прізвищ, вони не до всіх добре йдуть, тож решту будемо додавати, якщо буде потреба.
