### ISSUE TITLE
плутанина лем для :emph

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#62]
`adv:&pron:emph` є лемою для `adv:&pron:neg`, наприклад

<pre>нізвідки adv:&pron:<b>emph</b>
  нізвідки adv:&pron:<b>neg</b></pre>

Іменникові `emph` йдуть окремою лемою: 

<pre>нічим noun:inanim:v_oru:&pron:emph</pre> але якщо є два омоніми, то один стає лемою для іншого:
<pre>нічого noun:inanim:v_rod:&pron:emph
  нічого noun:inanim:v_zna:&pron:emph</pre>

**Comment by mariana-scorp** [comment]
Це я затикала з омонімією на наголоси. Виправлю.

**Comment by arysin** [comment]
Це можна закривати?

**Comment by Olvija** [comment]
@mariana-scorp, можна?

**Comment by arysin** [comment]
Ми зробили теги &pron:... ключем леми, тож тепер напр. &pron:neg та &pron:emph автоматично відокремлюються.
