### ISSUE TITLE
Ввести тег роду для множини

### ISSUE THREAD

**Issue by arysin** [brown-uk/dict_uk#73]
напр. 
вольтів вольт `noun:inanim:p:v_rod -> вольтів вольт noun:inanim:p:m:v_rod`

**Comment by msklvsk** [comment]
а воно показує емодзю
> <img width="247" alt="screen shot 2016-03-17 at 10 52 40" src="https://cloud.githubusercontent.com/assets/473012/13840923/67d4de60-ec2e-11e5-919b-25ca8484d6a3.png">

**Comment by arysin** [comment]
Ми проекспериментували з додаванням роду для множини (гілка gender_for_plurals), але, як виявилося, ця інформація надає дуже мало переваг і створює деякі проблеми, зокрема з прізвищами, іменниками подвійного роду тощо. Також часто рід множини можна визначити знайшовши лему слова. Тож наразі додавати рід множини в головну гілку не будемо.
