### ISSUE TITLE
Чи вставні потрібні як частина мови? 

### ISSUE THREAD

**Issue by natko5** [brown-uk/dict_uk#75]
Чи не достатньо було б мати "insert" як прапорець?
З граматично-семантичної точки зору це в основному модальні слова-фрази -- або дієслівні, або прислівникові, з різних семантичних груп. Вставне слово -- це поняття прагматики, використання; обробляється на інших рівнях. 
Взагалі це відкрита група, в добірці є непослідовності. От слово "зрозумійте" взяти -- те саме можна передати трохи складніше, наприклад:
зрозумійте мене
спробуйте зрозуміти
Вони мали б бути складеними вставними за тою логікою. Або чому тоді немає форми "зрозумій", синонімів до цього слова? Це стосується всіх віддієслівних. І так далі.
Слово "десь" туди помилково потрапило?
Більшість з тих слів, що закласифіковані як вставні, мають по кілька інтерпретацій. Тільки як вставні йдуть наступні (але їх теж легко приписати до морфосинтаксичних категорій, в основному прислівники або частки):

бува (як дієслово теж використовується)
будь-ласка (=будьте ласкаві)
далебі (бракує інтерпретації як частки)
далебіг
мабіть, мабуть, майбуть, мо (Чим вони суттєво відрізняються від "можливо"? Чому не мають інтерпретації прислівника?)
надісь
нажаль (=на превеликий жаль)
наприклад (=для прикладу)
простибі (=прости Боже)
простибіг

Нижче пропозиція з частковою аргументацією (СУМ або аналогії). 
1) дієслова залишаються тільки дієсловами, тобто без наступних:
бачиш
бачу
бува (додати дієслівну інтерпретацію)
виходить
даруйте
здавалося
здається
значить
зрозумійте
кажуть
скажімо 
сподіваюся
чуєте

Вийнятки: може і надісь

2) достатньо тагів, котрі вже є
безперечно adv:insert
безумовно adv:insert
видимо adv:insert
випадком adv:insert
власне part:insert
властиво part:insert (додати adv:insert)
зрештою adv:insert
либонь adv:insert
мабіть    adv:insert
мабуть    adv:insert
майбуть  adv:insert
мо    adv:insert
може    adv:insert
навпаки adv:insert
нарешті adv:insert
нівроку adv:insert
однак adv:insert
отже part:insert
очевидно adv:insert
по-вашому   adv:insert
по-друге adv:insert
по-моєму adv:insert
по-перше adv:insert
по-твоєму   adv:insert
прецінь part:insert, adv:insert
проте adv:insert
сількось adv:insert
справді part:insert, adv:insert
щоправда adv:insert

3) нові таги:
видно + adv:insert (пор. видимо)
мовляв +adv:insert (пор. прецінь)
надісь + part:insert (Уживається для підсилення достовірності висловленого у знач.мабуть, певно, можливо.)
наприклад + adv:insert
правда + adv:insert (пор.  Щоправда= Правду кажучи; правда, справді.)
далебі + part:insert (Уживається у знач. вставних слів: правду кажучи, справді [ж,бо], дійсно і т. ін. ; у знач. частки таки. )
далебіг + part:insert
простибі + adv:insert
простибіг + adv:insert (+ іменник, http://sum.in.ua/s/prostybi)

**Comment by natko5** [comment]
Або більш рестрикційний (і по-моєму слушний) варіант, де дієслова залишаються тільки дієсловами, тобто без наступних:
бачиш
бачу
бува (додати дієслівну інтерпретацію)
виходить
даруйте
здавалося
здається
значить
зрозумійте
кажуть
скажімо 
сподіваюся
чуєте

Вийнятки: може і надісь

**Comment by arysin** [comment]
Дякую за пропозицію, інтегрували в словник.
