### ISSUE TITLE
Окремий рядок dict_corp_viz на кожну конкретну інтерпретацію?

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#77]
Зараз однин рядок dict_corp_viz може кодувати одразу декілька морфологічних інтерпретацій. Скриптом знайшлися такі випадки де в рядку є по декілька прапорців однієї фічі:
1. `мігши :perf:imperf` (здається помилка, #76 )
2. `так conj:coord:subord` і `чи conj:coord:subord` — теж помилка?
3. відмінки `:rv_*`
4. типи займенників
5. альтернативні частини мови `:&_*`

Чому саме цих фіч (`:rv_*`, типів займенників), а не, скажімо, `:perf:imperf` чи навіть `:m:f` може бути по декілька на рядок? Чому не принцип “по рядку на інтерпретацію”?

**Comment by arysin** [comment]
1. виправили
2. не знаю, може @mariana-scorp прокоментує
3. щодо `:rv_` то це не є окремі морфологічні одиниці, це один й той самий прийменник, який може вимагати різних відмінків, тож тут один рядок виправданий.
4. @mariana-scorp
5. альтернативні частини з `:&_*` ми поки вирішили не розбивати, або не зрозуміло, як це добре зробити, або не має сенсу з погляду тегування/перервіки правил

**Comment by arysin** [comment]
Кожен рядок для однакових форм вносить омонімію, тож для випадків де омонімія не потрібна, інколи її майже неможливо зняти (зокрема для випадку adj/adjp) ми лишаємо тільки одну позицію.
perf/impef мають різне граматичне навантаження тож їх розносимо.
