### ISSUE TITLE
скільки-небудь numr:&pron, а ніскільки adv:&pron

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#80]
Несумісність?

І не існує тоді _ніскількох_.

**Comment by Olvija** [comment]
Так, слушно, для _ніскільки adv:&pron_ нема "ніскількох" ("Прунслик _ніскільки_ не здивувався, що пес говорить по-людськи" О.Гавриш. Розбійник Пинтя у заклятому місті).
Випадок _ніскількох ніскільки numr:&pron:v_rod**coll**_  ? ("А скількох взяли і посадили бодай для страхання? А _ніскількох_" В.Базів "Шлях з рабства").
Я пропонувала маркувати _ніскільки numr:&pron:nv_

**Comment by msklvsk** [comment]
Але ж у Прунстлика там прислівник? там _ніскільки_ = _ніяк_, а _ніяк_ _adv:&pron_.
Виходить, треба додати ще інтерпретацію числівника для другого речення. Додавати з `:coll`?

**Comment by arysin** [comment]
Таке враження, що ніскилькох — це щось дуже розмовне, а такого в жодних словниках не знайшов і навіть в худ. літ. дуже рідко зустрічається. Я б не додавав.

**Comment by vstarko** [comment]
Ніскільки має дві омонімічні леми: 1) прислівник adv; 2) займенник numr&pron. Друга лема має таке відмінювання, як "скільки", а перша не відмінюється. До першої леми я б не додавав &pron (так само в "аніскільки" - треба прибрати &pron). Немає потреби і в :coll, на мою думку. Ніскількох й справді рідко вживається, бо пасує хіба що як відповідь на "... скількох?". Але саме слово не діалектне, нормальне.

**Comment by arysin** [comment]
В нас купа слів на -скільки/-стільки і багато з них мають adv:&pron, якщо прибирати &pron то для всіх, але здається це було зроблено навмисно.
До речі скількись має adv, а скільки не має.
І чи треба тоді два омоніми для аніскільки?
І який буде тег, numr:&pron:neg ?
