### ISSUE TITLE
Безособова форма дієслів

### ISSUE THREAD

**Issue by msklvsk** [brown-uk/dict_uk#91]
Безособова форма зараз проставлена лише для чверті-третини дієслів (якщо правильно прикинув).

<pre>$ pcregrep 'imprs' data/dict/base.lst | wc -l
    5029
$ pcregrep '/v[^r]' data/dict/base.lst | pcregrep '^((?!imprs).)*$' | wc -l
   14384
</pre>

@arysin, Як найефективніше її проставити для решти? Чи лише руками, руками?

**Comment by arysin** [comment]
Безособова форма є не у всіх дієслів, схоже лише в перехідних і то можливо не у всіх.
Там є скриптик adjp_impers_check.groovy, який аналізує зв'язок дієприкметників і дієслів, можна його підкрутити, щоб побачити де є дієслова з відповідними дієприкметниками, але без безособової форми.

**Comment by arysin** [comment]
Я тут трішки пройшовся по нявним adjp де відстуні паралельні impers але з тисячі adjp там лише одиниці нових imprs (часто там теоретично може форма бути але в словниках і текстах не зустрічається). Тож схоже тут треба просто збирати impers що дійсно зустрічаються в текстах і додавати їх вручну.
Не знаю чи ти хочеш лишити це питання відкритим, чи це буде під загальною парасолькою збору нових слів/форм.

**Comment by vstarko** [comment]
@arysin чи міг би ти до всіх перехідних дієслів згенерувати безособові форми й прогнати ці слова на якомусь великому масиві текстів або в google books?

**Comment by arysin** [comment]
У нас наразі немає тегу перехідних дієслів, тож це непросто.

**Comment by vstarko** [comment]
тоді можна вчинити так: 
1. згенерувати для всіх дієслів (крім зворотних) або
2. згенерувати для всіх дієприслівників, просто помінявши -ий на -о.
І прогнати на текстах. Некоректні форми (від неперехідних) не буде знайдено - отже, не проблема. Буде трохи шуму (вдавано adv замість вдавано :impers), але й користі теж.
