### ISSUE TITLE
предикативи*

### ISSUE THREAD

**Issue by natko5** [brown-uk/dict_uk#97]
NB: Цей допис роблю на прохання @msklvsk, тема складна і неоднозначна, нею і для інших подібних мов ніхто толком не розібрався (в корпусних реалізаціях зокрема), але для протоколу хай буде.
Предикативи - це штучна категорія, на додаток дуже різношерстна, до якої часто потрапляють рідко вживані або слабо граматикалізовані (недо- або де-) лексичні одиниці, певного роду смітник, інакше кажучи. В українській лінгвістичній традиції це залишок російсько-радянських впливів. Вона прижилася ще в кількох соціалістичних сателітах (польська, болгарська, але напр. не чеська), хоча зараз від неї помалу і там позбуваються -- у сучасних комп’ютерно-лінгвістичних проектах предикативи є тільки у росіян. Відсутність їх у інших мовах можливо пов’язана із впливом багатомовних проектів або міжнародного лінгвістичного середовища загалом, де без предикативів спокійно обходяться, незважаючи на те, що багато де існують слова і явища, які описуються як предикативи в російській і наслідувачах. З практичної точки зору (подальше інтегрування української в багатомовних проектах) було б добре їх позбутися і в ВЕСУМ.
Запропонований перерозподіл тут: https://docs.google.com/spreadsheets/d/150NtuwcaqAvcaqYcFpKKDNdHfg6RmA2sUYCHJcx6l9M/edit?usp=sharing
Групування в межах предикативів ВЕСУМ (біля деяких слів -- таг MULTEXT-East):
короткі дієслівні форми, без закінчень, можуть стосуватися будь-яких особи, роду, числа: ців-ців, черк, мац, чик-чирик
модальні прислівники: варт(о), може, хтозна, слід, нічо-го R:mod
екзистенціальні занеговані дієслова: нема(є), катма; чортмає Vapip3s; чорт-мало Vapis3s; чорт-матиме Vapif3s
прислівники у порівняльному ступені: гірш, мерщій
прислівники із значенням стану: упам'ятку, упомки, упомку, тіняво, завізно (нота бене: такі слова складають ядро предикативів у російських граматиках/словниках; дивно, що в українській тільки ця пригоршня залишилася. Наприклад, слова “тісно”, “ясно” з тієї ж когорти.)
дієслівні форми на -но/то: походжено Vmeo
інші рідкісні дієслівні форми: любля Vmpip3s; ке Vmpm-2s, кете Vmpm-2p
іменники іноземного походження, що не повністю граматикалізувалися в українській: квити Ncmpnn; капут Ncmsnn, каюк
модальні прикметники: варт   Afpmsns
вигуки: спасибі I, також спасибі Ncnsnn; єсть Vmpsp (іноземне походження, не граматикалізоване в українській)
емфатичні або рефлексивні займенники: сам-один Px--m-sna, ні-чого Ph------r, ніяк Ph------r

Найбільше сумнівів у БМ викликали короткі дієслівні форми (зокрема вид, який при них подається). Зрозуміло, треба вводити нову категорію, але, якщо трохи покопатися, виявляється, що ідея зовсім не нова (крім виду, його аргументую якось при нагоді, але може хтось інтуїтивно вловить з матеріалу, про що мова). 
Ось тут є хороший матеріал: 
http://rus.1september.ru/article.php?ID=200202303 (Буслаєв)
http://rus.1september.ru/article.php?ID=200301102

Короткий огляд матеріалів з предикативів і їх представлення у граматиках кількох слов’янських мов є у цій статті (її вже пора заново переосмислити, правда):
Ivan Derzhanski and Natalia Kotsyba. The Category of Predicatives in the Light of Consistent Morphosyntactic Tagging. In "Lexicographic Tools and Techniques", Proceedings of MONDILEX First Open Workshop, Moscow, Russia, 3-4 October, 2008. Moscow 2008, p. 68-79. (Стягується з http://domeczek.pl/~natko/, 18.)

**Comment by vstarko** [comment]
Дякую за допис! Я теж за те, щоб позбутися класу предикативів. Виглядає так, що деякі слова можна безболісно зарахувати в інші, вже наявні класи: прислівників, займенників, вигуки. Вочевидь, нам потрібно буде ввести клас звуконаслідувань. Саме туди органічно можуть увійти слова на кшталт "черк". Залишиться групка таких, що нікуди так просто не пасують. Їх, я вважаю, варто буде просто позначити як незмінювані й утворити з них окремий клас (invar). Ясна річ, що класифікувати ці периферійні одиниці можна по-різному. Мені імпонує ідея збереження стрункості морфологічних класів, яка підказує, що для наших потреб (практичне застосування, морфаналіз, корпуси) ліпше запровадити нові класи (звуконаслідувальні слова та незмінювані слова) замість того, щоб, наприклад, вводити до класу дієслів незмінювані слова, що не мають жодних морфологічних ознак дієслова.

**Comment by arysin** [comment]
Ми щось схоже зробили з займенниками — розбили їх за іншими наявними класами, але залишили в кінці &pron. Не знаю, чи це варто також зробити для predic

**Comment by natko5** [comment]
@vstarko Мені здається, що терміни не дуже влучні: напр. "хить-хить" є візуальним сигналом, а не звуковим, взагалі їх діапазон ширший; більшість неповнозначних частин мови є незмінювана, тому інвар є щонайменше неінформативно. Та й введення нової категорії (читай: частини мови, у даному контексті) це трохи як міняти шило на мило. Морфологічної стрункості це не додасть. Єдине, що можна перетрясти вміст тої квазікатегорії в якийсь сенсовніший бік, але тоді вже немає значення, чи чистий залишок і надалі буде називатися предикативом, чи якось інакше.
Не знаю, чи ти читав статті Середи, на які я подала лінки. Вона там досить прозоро натякає, що у таких слів є основні ознаки дієслова -- стан, час -- які реалізуються у реченнях. Я ще б виловила вид на підставі повторюваності (редуплікація) або одноразовості дії. Але вид і так приписаний до леми, тому це в основному питання, до якої леми яку форму приписати (хоча воно може бути не таке тривіальне, як здається).
Моєю основною мотивацією, щоб залишити ці форми при дієсловах, було те, що вони функціонують як присудки -- практично повноцінні, тільки урізані особа і число.
Щодо "жодних морфологічних ознак дієслова", я б сказала, що у даному випадку є нульове закінчення (основа ж та сама залишається). Розумію, що то звучить трохи революційно :). Але незмінних дієслівних форм трохи є -- одною менше, одною більше...
@arysin Тут трохи інша ситуація, бо займенники є сенсовною граматичною групою, яку просто перекроїли, а "предикативи", принаймні так, як вони виділені в словнику -- ні. Сама ідея предикативів початково -- це те, що не є дієсловом, але виконує роль присудка, так туди потрапили короткі форми прикметників, прислівники, от тільки робилося це здебільшого непослідовно. То навіщо ця позначка, якщо вона тільки вносить плутанину.

**Comment by arysin** [comment]
Я не лінгвіст, але з точки погляду практичного використання тегів коли аналізувати тексти, то я б слова на штиб хить-хить до verb не заносив. Зокрема у нас є правила в LT які реагують на verb і переважно хить-хить в такі випадки не потрапляє. Окрім того зараз всі дієслова гарантовано мають ':imperf/:perf', а так доведеться робити виняток для цієї нової категорії.

**Comment by natko5** [comment]
Ми врешті це зробили інакше, я вже не вносила останні зміни до гугльдоку. Тільки тоді оті подвоєння треба окремо доаналізовувати, бо вони впливають на вид. Наразі картина отака:
(плюс "нерозлийвода" пішла до іменників)
походжено походити verb:imperf:impers

# perfective short verbs (acts)

хаміль хамільнути verb:pres:perf:act
шаміль шамільнути verb:pres:perf:act
блись блиснути verb:pres:perf:act
бусі буцнути verb:pres:perf:act
верть вертнути verb:pres:perf:act
гайда гайнути verb:pres:perf:act
гульк гулькнути verb:pres:perf:act
дейко дейко verb:pres:perf:act
зирк зиркнути verb:pres:perf:act
кап капнути verb:pres:perf:act
кив кивнути verb:pres:perf:act
кидь кинути verb:pres:perf:act
кихи кихнути verb:pres:perf:act
ковть ковтнути verb:pres:perf:act
крумк крумкнути verb:pres:perf:act
лулусь лулуснути verb:pres:perf:act
мац мацнути verb:pres:perf:act
пирск пирскнути verb:pres:perf:act
пуць пуцьнути verb:pres:perf:act
сіп сіпнути verb:pres:perf:act
скік скокнути verb:pres:perf:act
скіць скокнути verb:pres:perf:act
скок скокнути verb:pres:perf:act
смик смикнути verb:pres:perf:act
теліп теліпнути verb:pres:perf:act
торк торкнути verb:pres:perf:act
тріп тріпнути verb:pres:perf:act
трісь тріснути verb:pres:perf:act
фьюіть фьюітьнути verb:pres:perf:act
хвать хватнути verb:pres:perf:act
хвось хвосьнути verb:pres:perf:act
хить хитнути verb:pres:perf:act
хроп хропнути verb:pres:perf:act
хрум хрумнути verb:pres:perf:act
черк черкнути verb:pres:perf:act
черть чертнути verb:pres:perf:act
чирк чиркнути verb:pres:perf:act
шарк шаркнути verb:pres:perf:act
шасть шастнути verb:pres:perf:act
шелеп шелепнути verb:pres:perf:act
штирк штиркнути verb:pres:perf:act
бринь бринькнути verb:pres:perf:act
верть вертнути verb:pres:perf:act
круть крутнути verb:pres:perf:act
скік скочити verb:pres:perf:act
кліп кліпнути verb:pres:perf:act
нітелень теленькнути verb:pres:perf:act:neg
нічичирк чичиркнути verb:pres:perf:act:neg
трісь тріснути verb:pres:perf:act
тринь тринькнути verb:pres:perf:act
трюх трюхнути verb:pres:perf:act
трюхик трюхикнути verb:pres:perf:act
хавав хававнути verb:pres:perf:act
хаміль хамільнути verb:pres:perf:act
хить хитнути verb:pres:perf:act
ців цівнути verb:pres:perf:act
чикчирик чикчирикнути verb:pres:perf:act
чичирк чичиркнути verb:pres:perf:act
чухи чухнути verb:pres:perf:act
шаміль шамільнути verb:pres:perf:act
шкитильг шкитильгнути verb:pres:perf:act

# imperfective short verbs (acts)

балу балити verb:pres:imperf:act
галу галити verb:pres:imperf:act
тинини тинининати verb:pres:imperf:act
тирири тириририти verb:pres:imperf:act
тиририри тириририти verb:pres:imperf:act

# negative existentials

чорт-матиме чортмати verb:futr:s:3:imperf:neg
любля любляти verb:pres:s:3:imperf
катма катмати verb:pres:s:3:imperf:neg
катмає катмати verb:pres:s:3:imperf:neg
ма немати verb:pres:s:3:imperf:neg
нема немати verb:pres:s:3:imperf:neg
немає немати verb:pres:s:3:imperf:neg
немать немати verb:pres:s:3:imperf:neg
трясцяма трясцямати verb:pres:s:3:imperf:neg
чорт-ма чортмати verb:pres:s:3:imperf:neg
чортма чортмати verb:pres:s:3:imperf:neg
чортмає чортмати verb:pres:s:3:imperf:neg
чорт-мало чортмати verb:past:s:3:imperf:neg

# defective imperatives

гайда гайда verb:impr:s:2:imperf
гайдате гайда verb:impr:p:2:imperf
кете ке verb:impr:p:2:imperf
ке ке verb:impr:s:2:imperf
на на verb:impr:s:2:imperf
нате на verb:impr:p:2:imperf

**Comment by arysin** [comment]
Дякую за пропозицію, інтегрували в словник. 
Cхема трішки відрізняється від запропонованої, зокрема чортма, ке тощо отримали не verb з фіктивною лемою, а noninfl, також додали новий головний тег onomat для звуконаслідувальних слів (хоча там інколи досить складно знайти чітку межу), але головна ідея, здається, збережена.
Також ми (принаймні поки) не додавали тег `&predic` до безособових форм, бо їх дуже багато і можна автоматом знайти за `:impers`.
